import type { IconName } from '@/components/SiteIcon';
import type { Locale } from './i18n';

export const SITE_NAME = 'OnlineMediaTools';

export const SITE_DESCRIPTIONS: Record<Locale, string> = {
  en: 'AI transcription, subtitle generation, audio cleanup, and free media conversion tools online. No signup required. Files auto-delete after 2 hours.',
  fr: 'Transcription IA, génération de sous-titres, nettoyage audio et outils gratuits de conversion média en ligne. Sans inscription. Fichiers supprimés automatiquement après 2 heures.',
  es: 'Transcripción con IA, generación de subtítulos, limpieza de audio y herramientas gratis de conversión multimedia online. Sin registro. Los archivos se eliminan automáticamente después de 2 horas.',
};

export const COMMON_COPY = {
  en: {
    urlDownloader: {
      pasteUrl: 'Paste a video URL',
      urlPlaceholder: 'https://youtube.com/watch?v=...',
      invalidUrl: 'Please paste a valid URL starting with https://',
      videoFormat: 'Video (MP4)',
      audioFormat: 'Audio (MP3)',
      download: 'Download',
      processing: 'Downloading...',
      complete: 'Ready to download!',
      downloadVideo: 'Download MP4',
      downloadAudio: 'Download MP3',
      another: 'Download another',
      failed: 'Download failed. Please check the URL and try again.',
    },
    localeLabel: 'EN',
    localeNames: { en: 'English', fr: 'Français', es: 'Español' },
    languageMenuLabel: 'Languages',
    brandTagline: 'Free online video & audio tools. Convert, compress, extract, and optimize your media files.',
    nav: [
      ['All Tools', '/tools'],
      ['WebM to MP4', '/webm-to-mp4'],
      ['Transcribe Audio', '/transcribe-audio'],
      ['Auto Subtitles', '/auto-subtitle'],
      ['Compress', '/compress-video'],
    ],
    mobileNav: [
      ['All Tools', '/tools'],
      ['WebM to MP4', '/webm-to-mp4'],
      ['MOV to MP4', '/mov-to-mp4'],
      ['MP4 to MP3', '/mp4-to-mp3'],
      ['Transcribe Audio', '/transcribe-audio'],
      ['Auto Subtitles', '/auto-subtitle'],
      ['Translate Subtitles', '/translate-subtitles'],
      ['Clean Audio', '/clean-audio'],
      ['Compress', '/compress-video'],
      ['Trim Video', '/trim-video'],
    ],
    footer: {
      videoTools: 'Video Tools',
      audioTools: 'Audio Tools',
      legal: 'Legal',
      privacyPolicy: 'Privacy Policy',
      terms: 'Terms of Service',
      about: 'About',
      contact: 'Contact',
      cookiePreferences: 'Cookie preferences',
      legalText: 'By using this service, you confirm that you own or have permission to process all uploaded files. All uploads are automatically deleted after 2 hours.',
      copyright: 'Free Media Conversion Tools',
    },
    trustBadges: [
      { icon: 'noSignup' as IconName, title: 'No Signup Required', desc: 'Use all tools instantly' },
      { icon: 'secure' as IconName, title: 'Private & Secure', desc: 'Files never shared' },
      { icon: 'autoDelete' as IconName, title: 'Auto-Delete', desc: 'Deleted after 2 hours' },
      { icon: 'fastProcessing' as IconName, title: 'Fast Processing', desc: 'Powered by FFmpeg' },
    ],
    home: {
      badge: 'AI Transcription, Subtitles & Media Tools',
      title: 'Transcribe,',
      highlight: 'Subtitle,',
      titleSuffix: 'and Convert Media Online',
      descriptionTop: 'Generate transcripts, subtitles, translated captions, and cleaner audio in your browser.',
      descriptionBottom: 'Then convert, compress, trim, or extract media with the same no-signup workflow.',
      primaryCta: 'Transcribe Audio Free',
      secondaryCta: 'Generate Subtitles',
      popularTools: 'AI Transcription & Subtitle Tools',
      popularToolsSub: 'Start with the tools built for transcripts, captions, translation, and clearer voice audio.',
      allTools: 'AI Tools + Media Utilities',
      workflows: [
        {
          title: 'Transcribe meetings and interviews',
          body: 'Turn audio or video into editable text for notes, summaries, interview analysis, and first-pass content repurposing.',
        },
        {
          title: 'Generate and translate subtitles',
          body: 'Create SRT or VTT subtitle files, then translate them for multilingual publishing on YouTube, social, or internal training videos.',
        },
        {
          title: 'Clean audio, then convert or publish',
          body: 'Reduce background noise before exporting a transcript, generating subtitles, extracting audio, or preparing media for delivery.',
        },
      ],
      infoTitle: 'AI transcription first, supported by practical media tools',
      infoBody: [
        'OnlineMediaTools now focuses first on AI-powered transcription, subtitle generation, subtitle translation, and audio cleanup for common publishing and documentation workflows.',
        'Around those AI tools, the site also provides practical converters, compressors, trimmers, and audio extraction tools so you can clean, convert, and publish files in one browser-based flow.',
        'All files are processed securely on our servers and automatically deleted after 2 hours. No signup is required for quick tests, small one-off jobs, or repeat media tasks.',
      ],
      copyrightNoticeLabel: 'Copyright notice:',
      copyrightNoticeText: 'Only upload media that you own or have the legal right to process.',
      faq: [
        { q: 'Do the AI tools work with both audio and video?', a: 'Yes. The transcription, subtitle, translation, and audio cleanup tools all support common audio and video uploads such as MP3, WAV, MP4, MOV, and WebM.' },
        { q: 'Can I export transcripts and subtitle files?', a: 'Yes. Depending on the tool, you can export TXT, SRT, or VTT files for editing, publishing, and localization workflows.' },
        { q: 'What happens to my uploaded files?', a: 'Files are processed securely and automatically deleted after 2 hours. We never share your files.' },
        { q: 'Do I need to install software?', a: 'No. Everything runs in the browser with cloud processing. There is no local software to install.' },
        { q: 'Are the non-AI media tools still available?', a: 'Yes. You can still convert, compress, trim, extract audio, and remove audio with the same free workflow.' },
      ],
    },
    toolsPage: {
      badge: 'AI + Media Tools',
      title: 'Transcription, Subtitle, and Media Tools',
      subtitle: 'AI transcription and subtitle tools, plus essential converters, compressors, and audio utilities.',
      infoTitle: 'Choose the right tool by workflow',
      infoBody: [
        'The catalog now starts with AI-focused workflows such as transcription, automatic subtitles, subtitle translation, and audio cleanup. These pages are designed for captions, localization, meeting notes, interviews, podcasts, and publishing teams.',
        'Supporting those workflows, you still have the practical media utilities: format conversion, video compression, trimming, audio extraction, and audio or video cleanup before final export.',
      ],
    },
    shared: {
      faqTitle: 'Frequently Asked Questions',
      relatedToolsTitle: 'Related Tools',
      homeCrumb: 'Home',
      toolsCrumb: 'Tools',
      freeToolBadge: 'Free Online Tool',
      howToPrefix: 'How to use',
      supportedFormats: 'Supported Formats',
      commonUseCases: 'Common use cases',
      outputPrivacy: 'Output and privacy details',
      privacyText: 'Files are processed for the requested task and automatically deleted after 2 hours. You should only upload media that you own or have permission to process.',
      disclaimerTitle: 'Disclaimer:',
      disclaimerText: 'By uploading files, you confirm that you own or have explicit permission to process the uploaded media. Do not upload copyrighted content without authorization.',
      categories: {
        videoTools: 'Video Tools',
        audioTools: 'Audio Tools',
        aiTools: 'AI Tools',
      },
    },
    upload: {
      unsupportedType: 'Unsupported file type. Please upload one of: {supported}.',
      invalidTrim: 'Enter valid trim times using HH:MM:SS format.',
      invalidTrimOrder: 'End time must be later than the start time.',
      dropFile: 'Drop your file here',
      orBrowse: 'or',
      clickBrowse: 'click to browse',
      supports: 'Supports: {supported} - Max 200 MB',
      ready: 'Ready to process',
      uploading: 'Uploading...',
      ownership: 'By uploading, you confirm you own or have permission to process this file.',
      processAnother: 'Process another file',
      startingJob: 'Starting job...',
      processing: 'Processing your file...',
      failed: 'Processing failed. Please try again.',
      complete: 'Conversion complete!',
      download: 'Download File',
      availableUntil: 'File available until {time} (auto-deleted after 2h)',
      uploadFailed: 'Upload failed',
      statusFailed: 'Failed to get job status',
    },
    analyticsBanner: {
      title: 'Allow analytics cookies?',
      body: 'We use Google Analytics to understand which tools and calls to action perform best. Accepting analytics helps us improve the site. Declining keeps analytics disabled.',
      accept: 'Accept analytics',
      decline: 'Decline',
    },
  },
  fr: {
    urlDownloader: {
      pasteUrl: "Collez l'URL de la vidéo",
      urlPlaceholder: 'https://youtube.com/watch?v=...',
      invalidUrl: "Veuillez coller une URL valide commençant par https://",
      videoFormat: 'Vidéo (MP4)',
      audioFormat: 'Audio (MP3)',
      download: 'Télécharger',
      processing: 'Téléchargement...',
      complete: 'Prêt à télécharger !',
      downloadVideo: 'Télécharger MP4',
      downloadAudio: 'Télécharger MP3',
      another: 'Télécharger un autre',
      failed: "Échec du téléchargement. Vérifiez l'URL et réessayez.",
    },
    localeLabel: 'FR',
    localeNames: { en: 'English', fr: 'Français', es: 'Español' },
    languageMenuLabel: 'Langues',
    brandTagline: 'Outils vidéo et audio gratuits en ligne. Convertissez, compressez, extrayez et optimisez vos fichiers média.',
    nav: [
      ['Tous les outils', '/tools'],
      ['WebM vers MP4', '/webm-to-mp4'],
      ['Transcrire un audio', '/transcribe-audio'],
      ['Sous-titres auto', '/auto-subtitle'],
      ['Compresser', '/compress-video'],
    ],
    mobileNav: [
      ['Tous les outils', '/tools'],
      ['WebM vers MP4', '/webm-to-mp4'],
      ['MOV vers MP4', '/mov-to-mp4'],
      ['MP4 vers MP3', '/mp4-to-mp3'],
      ['Transcrire un audio', '/transcribe-audio'],
      ['Sous-titres auto', '/auto-subtitle'],
      ['Traduire les sous-titres', '/translate-subtitles'],
      ['Nettoyer l’audio', '/clean-audio'],
      ['Compresser', '/compress-video'],
      ['Couper une vidéo', '/trim-video'],
    ],
    footer: {
      videoTools: 'Outils vidéo',
      audioTools: 'Outils audio',
      legal: 'Mentions',
      privacyPolicy: 'Politique de confidentialité',
      terms: 'Conditions d’utilisation',
      about: 'À propos',
      contact: 'Contact',
      cookiePreferences: 'Préférences cookies',
      legalText: 'En utilisant ce service, vous confirmez que vous possédez les droits nécessaires pour traiter les fichiers envoyés. Tous les fichiers sont supprimés automatiquement après 2 heures.',
      copyright: 'Outils gratuits de conversion média',
    },
    trustBadges: [
      { icon: 'noSignup' as IconName, title: 'Sans inscription', desc: 'Utilisez les outils immédiatement' },
      { icon: 'secure' as IconName, title: 'Privé et sécurisé', desc: 'Fichiers jamais partagés' },
      { icon: 'autoDelete' as IconName, title: 'Suppression auto', desc: 'Supprimés après 2 heures' },
      { icon: 'fastProcessing' as IconName, title: 'Traitement rapide', desc: 'Propulsé par FFmpeg' },
    ],
    home: {
      badge: 'Transcription IA, sous-titres et outils média',
      title: 'Transcrire,',
      highlight: 'sous-titrer',
      titleSuffix: 'et convertir vos médias en ligne',
      descriptionTop: 'Générez des transcriptions, des sous-titres, des sous-titres traduits et un audio plus propre directement dans le navigateur.',
      descriptionBottom: 'Puis convertissez, compressez, coupez ou extrayez vos fichiers avec le même workflow sans inscription.',
      primaryCta: 'Transcrire un audio',
      secondaryCta: 'Générer des sous-titres',
      popularTools: 'Outils IA pour transcription et sous-titres',
      popularToolsSub: 'Commencez par les outils conçus pour les transcriptions, les légendes, la traduction et une voix plus claire.',
      allTools: 'Outils IA + utilitaires média',
      workflows: [
        {
          title: 'Transcrire réunions et interviews',
          body: 'Transformez un audio ou une vidéo en texte exploitable pour les comptes rendus, synthèses, interviews et premières réutilisations de contenu.',
        },
        {
          title: 'Générer et traduire des sous-titres',
          body: 'Créez des fichiers SRT ou VTT, puis traduisez-les pour une publication multilingue sur YouTube, les réseaux sociaux ou des vidéos de formation.',
        },
        {
          title: 'Nettoyer l’audio avant conversion ou publication',
          body: 'Réduisez le bruit de fond avant d’exporter une transcription, de générer des sous-titres, d’extraire l’audio ou de livrer un média final.',
        },
      ],
      infoTitle: 'La transcription IA d’abord, soutenue par des utilitaires média pratiques',
      infoBody: [
        'OnlineMediaTools met désormais en avant la transcription assistée par IA, la génération de sous-titres, la traduction de sous-titres et le nettoyage audio pour les workflows de publication et de documentation.',
        'Autour de ces outils IA, le site conserve des convertisseurs, compresseurs, outils de coupe et d’extraction audio afin de nettoyer, convertir et publier vos fichiers dans un seul flux navigateur.',
        'Tous les fichiers sont traités de manière sécurisée sur nos serveurs puis supprimés automatiquement après 2 heures. Aucun compte n’est nécessaire pour tester rapidement ou traiter des tâches récurrentes.',
      ],
      copyrightNoticeLabel: 'Droits d’auteur :',
      copyrightNoticeText: 'N’envoyez que des médias que vous possédez ou pour lesquels vous avez le droit de traitement.',
      faq: [
        { q: 'Les outils IA fonctionnent-ils avec l’audio et la vidéo ?', a: 'Oui. Les outils de transcription, sous-titres, traduction et nettoyage audio prennent en charge les formats audio et vidéo courants comme MP3, WAV, MP4, MOV et WebM.' },
        { q: 'Puis-je exporter des transcriptions et des fichiers de sous-titres ?', a: 'Oui. Selon l’outil, vous pouvez exporter des fichiers TXT, SRT ou VTT pour l’édition, la publication et la localisation.' },
        { q: 'Que deviennent mes fichiers envoyés ?', a: 'Les fichiers sont traités de façon sécurisée puis supprimés automatiquement après 2 heures. Ils ne sont jamais partagés.' },
        { q: 'Dois-je installer un logiciel ?', a: 'Non. Tout fonctionne dans le navigateur avec un traitement cloud. Aucun logiciel local à installer.' },
        { q: 'Les autres outils média sont-ils toujours disponibles ?', a: 'Oui. Vous pouvez toujours convertir, compresser, couper, extraire l’audio et supprimer l’audio avec le même workflow gratuit.' },
      ],
    },
    toolsPage: {
      badge: 'IA + outils média',
      title: 'Transcription, sous-titres et outils média',
      subtitle: 'Des outils de transcription et de sous-titres par IA, plus les convertisseurs, compresseurs et utilitaires audio essentiels.',
      infoTitle: 'Choisir l’outil selon votre workflow',
      infoBody: [
        'Le catalogue commence désormais par les workflows IA : transcription, sous-titres automatiques, traduction de sous-titres et nettoyage audio. Ces pages sont pensées pour les légendes, la localisation, les comptes rendus, les interviews, les podcasts et la publication.',
        'En complément, vous disposez toujours des utilitaires média utiles : conversion de formats, compression vidéo, coupe, extraction audio et préparation des fichiers avant export final.',
      ],
    },
    shared: {
      faqTitle: 'Questions fréquentes',
      relatedToolsTitle: 'Outils associés',
      homeCrumb: 'Accueil',
      toolsCrumb: 'Outils',
      freeToolBadge: 'Outil gratuit en ligne',
      howToPrefix: 'Comment utiliser',
      supportedFormats: 'Formats pris en charge',
      commonUseCases: 'Cas d’utilisation fréquents',
      outputPrivacy: 'Sortie et confidentialité',
      privacyText: 'Les fichiers sont traités pour la tâche demandée puis supprimés automatiquement après 2 heures. Vous devez uniquement envoyer des médias que vous avez le droit de traiter.',
      disclaimerTitle: 'Avertissement :',
      disclaimerText: 'En envoyant des fichiers, vous confirmez que vous possédez les droits nécessaires pour traiter les médias envoyés. N’envoyez pas de contenu protégé sans autorisation.',
      categories: {
        videoTools: 'Outils vidéo',
        audioTools: 'Outils audio',
        aiTools: 'Outils IA',
      },
    },
    upload: {
      unsupportedType: 'Type de fichier non pris en charge. Merci d’envoyer un fichier parmi : {supported}.',
      invalidTrim: 'Saisissez des heures valides au format HH:MM:SS.',
      invalidTrimOrder: 'L’heure de fin doit être postérieure à l’heure de début.',
      dropFile: 'Déposez votre fichier ici',
      orBrowse: 'ou',
      clickBrowse: 'cliquez pour parcourir',
      supports: 'Formats : {supported} - Max 200 Mo',
      ready: 'Prêt à être traité',
      uploading: 'Envoi en cours...',
      ownership: 'En envoyant un fichier, vous confirmez que vous avez le droit de le traiter.',
      processAnother: 'Traiter un autre fichier',
      startingJob: 'Démarrage du traitement...',
      processing: 'Traitement de votre fichier...',
      failed: 'Le traitement a échoué. Veuillez réessayer.',
      complete: 'Conversion terminée !',
      download: 'Télécharger le fichier',
      availableUntil: 'Fichier disponible jusqu’à {time} (suppression auto après 2h)',
      uploadFailed: 'Échec de l’envoi',
      statusFailed: 'Impossible de récupérer le statut du traitement',
    },
    analyticsBanner: {
      title: 'Autoriser les cookies analytics ?',
      body: 'Nous utilisons Google Analytics pour comprendre quels outils et appels à l’action performent le mieux. Accepter l’analytics nous aide à améliorer le site. Refuser garde l’analytics désactivé.',
      accept: 'Accepter l’analytics',
      decline: 'Refuser',
    },
  },
  es: {
    urlDownloader: {
      pasteUrl: 'Pega la URL del video',
      urlPlaceholder: 'https://youtube.com/watch?v=...',
      invalidUrl: 'Por favor pega una URL válida que comience con https://',
      videoFormat: 'Video (MP4)',
      audioFormat: 'Audio (MP3)',
      download: 'Descargar',
      processing: 'Descargando...',
      complete: '¡Listo para descargar!',
      downloadVideo: 'Descargar MP4',
      downloadAudio: 'Descargar MP3',
      another: 'Descargar otro',
      failed: 'Error al descargar. Verifica la URL e inténtalo de nuevo.',
    },
    localeLabel: 'ES',
    localeNames: { en: 'English', fr: 'Français', es: 'Español' },
    languageMenuLabel: 'Idiomas',
    brandTagline: 'Herramientas gratis online para video y audio. Convierte, comprime, extrae y optimiza tus archivos multimedia.',
    nav: [
      ['Todas las herramientas', '/tools'],
      ['WebM a MP4', '/webm-to-mp4'],
      ['Transcribir audio', '/transcribe-audio'],
      ['Subtítulos automáticos', '/auto-subtitle'],
      ['Comprimir', '/compress-video'],
    ],
    mobileNav: [
      ['Todas las herramientas', '/tools'],
      ['WebM a MP4', '/webm-to-mp4'],
      ['MOV a MP4', '/mov-to-mp4'],
      ['MP4 a MP3', '/mp4-to-mp3'],
      ['Transcribir audio', '/transcribe-audio'],
      ['Subtítulos automáticos', '/auto-subtitle'],
      ['Traducir subtítulos', '/translate-subtitles'],
      ['Limpiar audio', '/clean-audio'],
      ['Comprimir', '/compress-video'],
      ['Recortar video', '/trim-video'],
    ],
    footer: {
      videoTools: 'Herramientas de video',
      audioTools: 'Herramientas de audio',
      legal: 'Legal',
      privacyPolicy: 'Política de privacidad',
      terms: 'Términos del servicio',
      about: 'Acerca de',
      contact: 'Contacto',
      cookiePreferences: 'Preferencias de cookies',
      legalText: 'Al usar este servicio, confirmas que eres propietario de los archivos subidos o que tienes permiso para procesarlos. Todos los archivos se eliminan automáticamente después de 2 horas.',
      copyright: 'Herramientas gratuitas de conversión multimedia',
    },
    trustBadges: [
      { icon: 'noSignup' as IconName, title: 'Sin registro', desc: 'Usa todas las herramientas al instante' },
      { icon: 'secure' as IconName, title: 'Privado y seguro', desc: 'Los archivos nunca se comparten' },
      { icon: 'autoDelete' as IconName, title: 'Eliminación automática', desc: 'Se borran después de 2 horas' },
      { icon: 'fastProcessing' as IconName, title: 'Procesamiento rápido', desc: 'Impulsado por FFmpeg' },
    ],
    home: {
      badge: 'Transcripción IA, subtítulos y herramientas multimedia',
      title: 'Transcribe,',
      highlight: 'subtitula',
      titleSuffix: 'y convierte archivos online',
      descriptionTop: 'Genera transcripciones, subtítulos, subtítulos traducidos y audio más limpio directamente en el navegador.',
      descriptionBottom: 'Después convierte, comprime, recorta o extrae archivos con el mismo flujo sin registro.',
      primaryCta: 'Transcribir audio',
      secondaryCta: 'Generar subtítulos',
      popularTools: 'Herramientas IA para transcripción y subtítulos',
      popularToolsSub: 'Empieza con las herramientas pensadas para transcripciones, captions, traducción y voz más clara.',
      allTools: 'Herramientas IA + utilidades multimedia',
      workflows: [
        {
          title: 'Transcribir reuniones y entrevistas',
          body: 'Convierte audio o video en texto editable para notas, resúmenes, análisis de entrevistas y reutilización inicial de contenido.',
        },
        {
          title: 'Generar y traducir subtítulos',
          body: 'Crea archivos SRT o VTT y tradúcelos para publicar en varios idiomas en YouTube, redes sociales o videos de formación.',
        },
        {
          title: 'Limpiar audio antes de convertir o publicar',
          body: 'Reduce el ruido de fondo antes de exportar una transcripción, generar subtítulos, extraer audio o preparar el archivo final.',
        },
      ],
      infoTitle: 'Primero transcripción IA, respaldada por utilidades multimedia',
      infoBody: [
        'OnlineMediaTools ahora prioriza la transcripción con IA, la generación automática de subtítulos, la traducción de subtítulos y la limpieza de audio para flujos de publicación y documentación.',
        'Alrededor de esas herramientas IA, el sitio mantiene convertidores, compresores, recorte y extracción de audio para limpiar, convertir y publicar archivos dentro del mismo flujo en navegador.',
        'Todos los archivos se procesan de forma segura en nuestros servidores y se eliminan automáticamente después de 2 horas. No se requiere registro para pruebas rápidas ni para tareas repetitivas.',
      ],
      copyrightNoticeLabel: 'Aviso de copyright:',
      copyrightNoticeText: 'Solo sube archivos multimedia que poseas o que tengas derecho legal a procesar.',
      faq: [
        { q: '¿Las herramientas IA funcionan con audio y video?', a: 'Sí. Las herramientas de transcripción, subtítulos, traducción y limpieza de audio admiten formatos comunes como MP3, WAV, MP4, MOV y WebM.' },
        { q: '¿Puedo exportar transcripciones y archivos de subtítulos?', a: 'Sí. Según la herramienta, puedes exportar archivos TXT, SRT o VTT para edición, publicación y localización.' },
        { q: '¿Qué ocurre con mis archivos subidos?', a: 'Los archivos se procesan de forma segura y se eliminan automáticamente después de 2 horas. Nunca se comparten.' },
        { q: '¿Necesito instalar software?', a: 'No. Todo funciona en el navegador con procesamiento en la nube. No necesitas instalar nada.' },
        { q: '¿Siguen disponibles las demás herramientas multimedia?', a: 'Sí. Todavía puedes convertir, comprimir, recortar, extraer audio y eliminar audio con el mismo flujo gratuito.' },
      ],
    },
    toolsPage: {
      badge: 'IA + herramientas multimedia',
      title: 'Transcripción, subtítulos y herramientas multimedia',
      subtitle: 'Herramientas IA de transcripción y subtítulos, además de convertidores, compresores y utilidades de audio esenciales.',
      infoTitle: 'Elige la herramienta según tu flujo',
      infoBody: [
        'El catálogo empieza ahora con flujos centrados en IA: transcripción, subtítulos automáticos, traducción de subtítulos y limpieza de audio. Estas páginas están pensadas para captions, localización, notas de reuniones, entrevistas, podcasts y publicación.',
        'Como soporte, siguen disponibles las utilidades multimedia prácticas: conversión de formatos, compresión de video, recorte, extracción de audio y preparación de archivos antes de la exportación final.',
      ],
    },
    shared: {
      faqTitle: 'Preguntas frecuentes',
      relatedToolsTitle: 'Herramientas relacionadas',
      homeCrumb: 'Inicio',
      toolsCrumb: 'Herramientas',
      freeToolBadge: 'Herramienta gratis online',
      howToPrefix: 'Cómo usar',
      supportedFormats: 'Formatos compatibles',
      commonUseCases: 'Casos de uso comunes',
      outputPrivacy: 'Salida y privacidad',
      privacyText: 'Los archivos se procesan para la tarea solicitada y se eliminan automáticamente después de 2 horas. Solo debes subir contenido multimedia que sea tuyo o que tengas permiso para procesar.',
      disclaimerTitle: 'Aviso:',
      disclaimerText: 'Al subir archivos, confirmas que eres el propietario o que tienes permiso explícito para procesar el contenido subido. No subas material con copyright sin autorización.',
      categories: {
        videoTools: 'Herramientas de video',
        audioTools: 'Herramientas de audio',
        aiTools: 'Herramientas con IA',
      },
    },
    upload: {
      unsupportedType: 'Tipo de archivo no compatible. Sube uno de estos formatos: {supported}.',
      invalidTrim: 'Introduce tiempos válidos con el formato HH:MM:SS.',
      invalidTrimOrder: 'La hora de fin debe ser posterior a la de inicio.',
      dropFile: 'Suelta tu archivo aquí',
      orBrowse: 'o',
      clickBrowse: 'haz clic para buscar',
      supports: 'Compatible con: {supported} - Máx 200 MB',
      ready: 'Listo para procesar',
      uploading: 'Subiendo...',
      ownership: 'Al subir un archivo, confirmas que eres propietario del contenido o que tienes permiso para procesarlo.',
      processAnother: 'Procesar otro archivo',
      startingJob: 'Iniciando proceso...',
      processing: 'Procesando tu archivo...',
      failed: 'El procesamiento falló. Inténtalo de nuevo.',
      complete: '¡Conversión completada!',
      download: 'Descargar archivo',
      availableUntil: 'Archivo disponible hasta {time} (eliminación automática tras 2h)',
      uploadFailed: 'Error al subir el archivo',
      statusFailed: 'No se pudo obtener el estado del proceso',
    },
    analyticsBanner: {
      title: '¿Permitir cookies de analytics?',
      body: 'Usamos Google Analytics para entender qué herramientas y llamadas a la acción funcionan mejor. Aceptar analytics nos ayuda a mejorar el sitio. Rechazar mantiene analytics desactivado.',
      accept: 'Aceptar analytics',
      decline: 'Rechazar',
    },
  },
} satisfies Record<Locale, unknown>;

export function getCopy(locale: Locale) {
  return COMMON_COPY[locale];
}
