import type { IconName } from '@/components/SiteIcon';
import type { Locale } from './i18n';

export const SITE_NAME = 'OnlineMediaTools';

export const SITE_DESCRIPTIONS: Record<Locale, string> = {
  en: 'Free online video and audio tools for converting, compressing, trimming, and extracting audio. No signup required. Files auto-delete after 2 hours.',
  fr: 'Outils gratuits en ligne pour convertir, compresser, couper des vidéos et extraire l’audio. Sans inscription. Fichiers supprimés automatiquement après 2 heures.',
  es: 'Herramientas gratis online para convertir, comprimir, recortar videos y extraer audio. Sin registro. Los archivos se eliminan automáticamente después de 2 horas.',
};

export const COMMON_COPY = {
  en: {
    localeLabel: 'EN',
    localeNames: { en: 'English', fr: 'Français', es: 'Español' },
    languageMenuLabel: 'Languages',
    brandTagline: 'Free online video & audio tools. Convert, compress, extract, and optimize your media files.',
    nav: [
      ['All Tools', '/tools'],
      ['WebM to MP4', '/webm-to-mp4'],
      ['MP4 to MP3', '/mp4-to-mp3'],
      ['Compress', '/compress-video'],
      ['Trim Video', '/trim-video'],
    ],
    mobileNav: [
      ['All Tools', '/tools'],
      ['WebM to MP4', '/webm-to-mp4'],
      ['MOV to MP4', '/mov-to-mp4'],
      ['MP4 to MP3', '/mp4-to-mp3'],
      ['Compress', '/compress-video'],
      ['Trim Video', '/trim-video'],
    ],
    footer: {
      videoTools: 'Video Tools',
      audioTools: 'Audio Tools',
      legal: 'Legal',
      legalText: 'By using this service, you confirm that you own or have permission to process all uploaded files. All uploads are automatically deleted after 2 hours.',
      copyright: 'Free Media Conversion Tools',
    },
    trustBadges: [
      { icon: 'noSignup' as IconName, title: 'No Signup Required', desc: 'Use all tools instantly' },
      { icon: 'secure' as IconName, title: 'Private & Secure', desc: 'Files never shared' },
      { icon: 'autoDelete' as IconName, title: 'Auto-Delete', desc: 'Deleted after 2 hours' },
      { icon: 'fastProcessing' as IconName, title: 'Fast Processing', desc: 'Powered by FFmpeg' },
    ],
    home: {
      badge: '100% Free - No Signup Required',
      title: 'Free Online',
      highlight: 'Video & Audio',
      titleSuffix: 'Tools',
      descriptionTop: 'Convert, compress, extract, and optimize your media files online.',
      descriptionBottom: 'Fast, secure, and completely free.',
      primaryCta: 'Start Converting',
      secondaryCta: 'View All Tools',
      popularTools: 'Popular Tools',
      popularToolsSub: 'Most used media processing tools',
      allTools: 'All Media Tools',
      workflows: [
        {
          title: 'Quick format conversion',
          body: 'Convert browser recordings, iPhone videos, or mixed media files into formats that are easier to upload, edit, and share.',
        },
        {
          title: 'Audio extraction and cleanup',
          body: 'Pull MP3, WAV, or AAC from your videos when you only need the soundtrack, lecture, or interview audio.',
        },
        {
          title: 'Trim and compress before sharing',
          body: 'Shorten long clips and reduce file size before posting online, sending files over chat, or attaching media to email.',
        },
      ],
      infoTitle: 'Free Online Media Processing Tools',
      infoBody: [
        'OnlineMediaTools provides a focused suite of browser-based video and audio utilities powered by FFmpeg. You can convert formats, extract audio, compress files, trim clips, and remove audio without installing software.',
        'Every tool is designed for direct use in a modern browser with simple upload, process, and download steps. That makes the site useful for quick one-off tasks, repeated publishing workflows, and lightweight media cleanup.',
        'All files are processed securely on our servers and permanently deleted after 2 hours. We never share or analyze your content for advertising or training purposes.',
      ],
      copyrightNoticeLabel: 'Copyright notice:',
      copyrightNoticeText: 'Only upload media that you own or have the legal right to process.',
      faq: [
        { q: 'Are all tools really free?', a: 'Yes. All tools on OnlineMediaTools are completely free with no sign-up required.' },
        { q: 'What happens to my uploaded files?', a: 'Files are processed securely and automatically deleted after 2 hours. We never share your files.' },
        { q: 'What is the maximum file size?', a: 'You can upload files up to 200 MB.' },
        { q: 'Do I need to install software?', a: 'No. Everything runs in the cloud. No downloads needed.' },
        { q: 'Is it safe to upload my files?', a: 'Yes. Files are stored securely, processed, and deleted automatically. We never analyze file content.' },
      ],
    },
    toolsPage: {
      badge: 'Free Tools',
      title: 'All Media Tools',
      subtitle: 'Free online tools for video and audio processing',
      infoTitle: 'What you can do here',
      infoBody: [
        'The tools catalog covers common media tasks such as converting WebM or MOV to MP4, extracting audio from video, trimming clips, compressing large uploads, and converting audio between major formats.',
        'Each page includes the supported input formats, output format, file-handling expectations, and a focused workflow for the task. That keeps the site easier to scan for users and easier to understand for search crawlers.',
      ],
    },
    shared: {
      faqTitle: 'Frequently Asked Questions',
      relatedToolsTitle: 'Related Tools',
      homeCrumb: 'Home',
      toolsCrumb: 'Tools',
      freeToolBadge: 'Free Online Tool',
      howToPrefix: 'How to use',
      supportedFormats: 'Supported Formats',
      commonUseCases: 'Common use cases',
      outputPrivacy: 'Output and privacy details',
      privacyText: 'Files are processed for the requested task and automatically deleted after 2 hours. You should only upload media that you own or have permission to process.',
      disclaimerTitle: 'Disclaimer:',
      disclaimerText: 'By uploading files, you confirm that you own or have explicit permission to process the uploaded media. Do not upload copyrighted content without authorization.',
      categories: {
        videoTools: 'Video Tools',
        audioTools: 'Audio Tools',
      },
    },
    upload: {
      unsupportedType: 'Unsupported file type. Please upload one of: {supported}.',
      invalidTrim: 'Enter valid trim times using HH:MM:SS format.',
      invalidTrimOrder: 'End time must be later than the start time.',
      dropFile: 'Drop your file here',
      orBrowse: 'or',
      clickBrowse: 'click to browse',
      supports: 'Supports: {supported} - Max 200 MB',
      ready: 'Ready to process',
      uploading: 'Uploading...',
      ownership: 'By uploading, you confirm you own or have permission to process this file.',
      processAnother: 'Process another file',
      startingJob: 'Starting job...',
      processing: 'Processing your file...',
      failed: 'Processing failed. Please try again.',
      complete: 'Conversion complete!',
      download: 'Download File',
      availableUntil: 'File available until {time} (auto-deleted after 2h)',
      uploadFailed: 'Upload failed',
      statusFailed: 'Failed to get job status',
    },
  },
  fr: {
    localeLabel: 'FR',
    localeNames: { en: 'English', fr: 'Français', es: 'Español' },
    languageMenuLabel: 'Langues',
    brandTagline: 'Outils vidéo et audio gratuits en ligne. Convertissez, compressez, extrayez et optimisez vos fichiers média.',
    nav: [
      ['Tous les outils', '/tools'],
      ['WebM vers MP4', '/webm-to-mp4'],
      ['MP4 vers MP3', '/mp4-to-mp3'],
      ['Compresser', '/compress-video'],
      ['Couper une vidéo', '/trim-video'],
    ],
    mobileNav: [
      ['Tous les outils', '/tools'],
      ['WebM vers MP4', '/webm-to-mp4'],
      ['MOV vers MP4', '/mov-to-mp4'],
      ['MP4 vers MP3', '/mp4-to-mp3'],
      ['Compresser', '/compress-video'],
      ['Couper une vidéo', '/trim-video'],
    ],
    footer: {
      videoTools: 'Outils vidéo',
      audioTools: 'Outils audio',
      legal: 'Mentions',
      legalText: 'En utilisant ce service, vous confirmez que vous possédez les droits nécessaires pour traiter les fichiers envoyés. Tous les fichiers sont supprimés automatiquement après 2 heures.',
      copyright: 'Outils gratuits de conversion média',
    },
    trustBadges: [
      { icon: 'noSignup' as IconName, title: 'Sans inscription', desc: 'Utilisez les outils immédiatement' },
      { icon: 'secure' as IconName, title: 'Privé et sécurisé', desc: 'Fichiers jamais partagés' },
      { icon: 'autoDelete' as IconName, title: 'Suppression auto', desc: 'Supprimés après 2 heures' },
      { icon: 'fastProcessing' as IconName, title: 'Traitement rapide', desc: 'Propulsé par FFmpeg' },
    ],
    home: {
      badge: '100% gratuit - Sans inscription',
      title: 'Convertisseur',
      highlight: 'Vidéo & Audio',
      titleSuffix: 'gratuit en ligne',
      descriptionTop: 'Convertissez, compressez, extrayez et optimisez vos fichiers média en ligne.',
      descriptionBottom: 'Rapide, sécurisé et totalement gratuit.',
      primaryCta: 'Commencer',
      secondaryCta: 'Voir tous les outils',
      popularTools: 'Outils populaires',
      popularToolsSub: 'Les outils les plus utilisés',
      allTools: 'Tous les outils média',
      workflows: [
        {
          title: 'Conversion rapide de formats',
          body: 'Convertissez des enregistrements navigateur, des vidéos iPhone ou des fichiers mixtes vers des formats plus simples à partager, éditer et publier.',
        },
        {
          title: 'Extraction et nettoyage audio',
          body: 'Récupérez du MP3, WAV ou AAC à partir de vos vidéos quand vous n’avez besoin que de la bande-son, d’un cours ou d’une interview.',
        },
        {
          title: 'Couper et compresser avant partage',
          body: 'Raccourcissez les longs clips et réduisez leur taille avant de les publier, envoyer par messagerie ou joindre à un e-mail.',
        },
      ],
      infoTitle: 'Outils gratuits de traitement média en ligne',
      infoBody: [
        'OnlineMediaTools propose une suite ciblée d’outils vidéo et audio basés sur FFmpeg. Vous pouvez convertir des formats, extraire l’audio, compresser des fichiers, couper des clips et supprimer des pistes audio sans installer de logiciel.',
        'Chaque outil est conçu pour une utilisation directe dans un navigateur moderne avec un flux simple : envoyer, traiter, télécharger. Cela rend le site utile pour les besoins rapides comme pour les petits workflows récurrents.',
        'Tous les fichiers sont traités de manière sécurisée sur nos serveurs puis supprimés automatiquement après 2 heures. Nous ne partageons pas vos fichiers et ne les analysons pas à des fins publicitaires ou d’entraînement.',
      ],
      copyrightNoticeLabel: 'Droits d’auteur :',
      copyrightNoticeText: 'N’envoyez que des médias que vous possédez ou pour lesquels vous avez le droit de traitement.',
      faq: [
        { q: 'Tous les outils sont-ils vraiment gratuits ?', a: 'Oui. Tous les outils OnlineMediaTools sont entièrement gratuits et ne nécessitent pas de compte.' },
        { q: 'Que deviennent mes fichiers envoyés ?', a: 'Les fichiers sont traités de façon sécurisée puis supprimés automatiquement après 2 heures. Ils ne sont jamais partagés.' },
        { q: 'Quelle est la taille maximale ?', a: 'Vous pouvez envoyer des fichiers jusqu’à 200 Mo.' },
        { q: 'Dois-je installer un logiciel ?', a: 'Non. Tout fonctionne dans le cloud, sans téléchargement local.' },
        { q: 'Est-ce sûr d’envoyer mes fichiers ?', a: 'Oui. Les fichiers sont stockés et traités de façon sécurisée puis supprimés automatiquement. Nous n’analysons pas leur contenu.' },
      ],
    },
    toolsPage: {
      badge: 'Outils gratuits',
      title: 'Tous les outils vidéo et audio',
      subtitle: 'Convertir, compresser, couper et extraire l’audio de vos fichiers vidéo et audio en ligne',
      infoTitle: 'Ce que vous pouvez faire ici',
      infoBody: [
        'Le catalogue couvre les tâches média courantes : convertir du WebM ou MOV vers MP4, extraire l’audio d’une vidéo, couper des clips, compresser de gros fichiers et convertir des formats audio.',
        'Chaque page indique les formats d’entrée pris en charge, le format de sortie, les règles de gestion des fichiers et un workflow simple pour accomplir la tâche rapidement.',
      ],
    },
    shared: {
      faqTitle: 'Questions fréquentes',
      relatedToolsTitle: 'Outils associés',
      homeCrumb: 'Accueil',
      toolsCrumb: 'Outils',
      freeToolBadge: 'Outil gratuit en ligne',
      howToPrefix: 'Comment utiliser',
      supportedFormats: 'Formats pris en charge',
      commonUseCases: 'Cas d’utilisation fréquents',
      outputPrivacy: 'Sortie et confidentialité',
      privacyText: 'Les fichiers sont traités pour la tâche demandée puis supprimés automatiquement après 2 heures. Vous devez uniquement envoyer des médias que vous avez le droit de traiter.',
      disclaimerTitle: 'Avertissement :',
      disclaimerText: 'En envoyant des fichiers, vous confirmez que vous possédez les droits nécessaires pour traiter les médias envoyés. N’envoyez pas de contenu protégé sans autorisation.',
      categories: {
        videoTools: 'Outils vidéo',
        audioTools: 'Outils audio',
      },
    },
    upload: {
      unsupportedType: 'Type de fichier non pris en charge. Merci d’envoyer un fichier parmi : {supported}.',
      invalidTrim: 'Saisissez des heures valides au format HH:MM:SS.',
      invalidTrimOrder: 'L’heure de fin doit être postérieure à l’heure de début.',
      dropFile: 'Déposez votre fichier ici',
      orBrowse: 'ou',
      clickBrowse: 'cliquez pour parcourir',
      supports: 'Formats : {supported} - Max 200 Mo',
      ready: 'Prêt à être traité',
      uploading: 'Envoi en cours...',
      ownership: 'En envoyant un fichier, vous confirmez que vous avez le droit de le traiter.',
      processAnother: 'Traiter un autre fichier',
      startingJob: 'Démarrage du traitement...',
      processing: 'Traitement de votre fichier...',
      failed: 'Le traitement a échoué. Veuillez réessayer.',
      complete: 'Conversion terminée !',
      download: 'Télécharger le fichier',
      availableUntil: 'Fichier disponible jusqu’à {time} (suppression auto après 2h)',
      uploadFailed: 'Échec de l’envoi',
      statusFailed: 'Impossible de récupérer le statut du traitement',
    },
  },
  es: {
    localeLabel: 'ES',
    localeNames: { en: 'English', fr: 'Français', es: 'Español' },
    languageMenuLabel: 'Idiomas',
    brandTagline: 'Herramientas gratis online para video y audio. Convierte, comprime, extrae y optimiza tus archivos multimedia.',
    nav: [
      ['Todas las herramientas', '/tools'],
      ['WebM a MP4', '/webm-to-mp4'],
      ['MP4 a MP3', '/mp4-to-mp3'],
      ['Comprimir', '/compress-video'],
      ['Recortar video', '/trim-video'],
    ],
    mobileNav: [
      ['Todas las herramientas', '/tools'],
      ['WebM a MP4', '/webm-to-mp4'],
      ['MOV a MP4', '/mov-to-mp4'],
      ['MP4 a MP3', '/mp4-to-mp3'],
      ['Comprimir', '/compress-video'],
      ['Recortar video', '/trim-video'],
    ],
    footer: {
      videoTools: 'Herramientas de video',
      audioTools: 'Herramientas de audio',
      legal: 'Legal',
      legalText: 'Al usar este servicio, confirmas que eres propietario de los archivos subidos o que tienes permiso para procesarlos. Todos los archivos se eliminan automáticamente después de 2 horas.',
      copyright: 'Herramientas gratuitas de conversión multimedia',
    },
    trustBadges: [
      { icon: 'noSignup' as IconName, title: 'Sin registro', desc: 'Usa todas las herramientas al instante' },
      { icon: 'secure' as IconName, title: 'Privado y seguro', desc: 'Los archivos nunca se comparten' },
      { icon: 'autoDelete' as IconName, title: 'Eliminación automática', desc: 'Se borran después de 2 horas' },
      { icon: 'fastProcessing' as IconName, title: 'Procesamiento rápido', desc: 'Impulsado por FFmpeg' },
    ],
    home: {
      badge: '100% gratis - Sin registro',
      title: 'Convertidor',
      highlight: 'de Video y Audio',
      titleSuffix: 'gratis online',
      descriptionTop: 'Convierte, comprime, extrae y optimiza tus archivos multimedia online.',
      descriptionBottom: 'Rápido, seguro y totalmente gratis.',
      primaryCta: 'Empezar a convertir',
      secondaryCta: 'Ver todas las herramientas',
      popularTools: 'Herramientas populares',
      popularToolsSub: 'Las herramientas multimedia más utilizadas',
      allTools: 'Todas las herramientas multimedia',
      workflows: [
        {
          title: 'Conversión rápida de formatos',
          body: 'Convierte grabaciones del navegador, videos de iPhone o archivos mixtos a formatos más fáciles de subir, editar y compartir.',
        },
        {
          title: 'Extracción y limpieza de audio',
          body: 'Extrae MP3, WAV o AAC de tus videos cuando solo necesitas la pista de audio, una clase o una entrevista.',
        },
        {
          title: 'Recorta y comprime antes de compartir',
          body: 'Acorta clips largos y reduce su tamaño antes de publicarlos, enviarlos por chat o adjuntarlos a un correo.',
        },
      ],
      infoTitle: 'Herramientas gratis de procesamiento multimedia online',
      infoBody: [
        'OnlineMediaTools ofrece un conjunto enfocado de utilidades de video y audio basadas en FFmpeg. Puedes convertir formatos, extraer audio, comprimir archivos, recortar clips y eliminar audio sin instalar software.',
        'Cada herramienta está pensada para usarse directamente en un navegador moderno con un flujo simple de subir, procesar y descargar. Esto hace que el sitio sea útil para tareas puntuales y para flujos de trabajo ligeros repetidos.',
        'Todos los archivos se procesan de forma segura en nuestros servidores y se eliminan permanentemente después de 2 horas. Nunca compartimos ni analizamos tu contenido con fines publicitarios o de entrenamiento.',
      ],
      copyrightNoticeLabel: 'Aviso de derechos de autor:',
      copyrightNoticeText: 'Sube únicamente archivos multimedia que sean tuyos o para los que tengas permiso legal de procesamiento.',
      faq: [
        { q: '¿Todas las herramientas son realmente gratis?', a: 'Sí. Todas las herramientas de OnlineMediaTools son completamente gratis y no requieren registro.' },
        { q: '¿Qué pasa con mis archivos subidos?', a: 'Los archivos se procesan de forma segura y se eliminan automáticamente después de 2 horas. Nunca se comparten.' },
        { q: '¿Cuál es el tamaño máximo de archivo?', a: 'Puedes subir archivos de hasta 200 MB.' },
        { q: '¿Necesito instalar software?', a: 'No. Todo funciona en la nube. No necesitas descargar nada.' },
        { q: '¿Es seguro subir mis archivos?', a: 'Sí. Los archivos se almacenan y procesan de forma segura y luego se eliminan automáticamente. No analizamos su contenido.' },
      ],
    },
    toolsPage: {
      badge: 'Herramientas gratis',
      title: 'Todas las herramientas de video y audio',
      subtitle: 'Convertir, comprimir, recortar y extraer audio de archivos de video y audio online',
      infoTitle: 'Qué puedes hacer aquí',
      infoBody: [
        'El catálogo cubre tareas multimedia comunes como convertir WebM o MOV a MP4, extraer audio de video, recortar clips, comprimir archivos grandes y convertir entre formatos de audio populares.',
        'Cada página incluye los formatos de entrada compatibles, el formato de salida, las condiciones de manejo de archivos y un flujo de trabajo claro para completar la tarea rápidamente.',
      ],
    },
    shared: {
      faqTitle: 'Preguntas frecuentes',
      relatedToolsTitle: 'Herramientas relacionadas',
      homeCrumb: 'Inicio',
      toolsCrumb: 'Herramientas',
      freeToolBadge: 'Herramienta gratis online',
      howToPrefix: 'Cómo usar',
      supportedFormats: 'Formatos compatibles',
      commonUseCases: 'Casos de uso comunes',
      outputPrivacy: 'Salida y privacidad',
      privacyText: 'Los archivos se procesan para la tarea solicitada y se eliminan automáticamente después de 2 horas. Solo debes subir contenido multimedia que sea tuyo o que tengas permiso para procesar.',
      disclaimerTitle: 'Aviso:',
      disclaimerText: 'Al subir archivos, confirmas que eres el propietario o que tienes permiso explícito para procesar el contenido subido. No subas material con copyright sin autorización.',
      categories: {
        videoTools: 'Herramientas de video',
        audioTools: 'Herramientas de audio',
      },
    },
    upload: {
      unsupportedType: 'Tipo de archivo no compatible. Sube uno de estos formatos: {supported}.',
      invalidTrim: 'Introduce tiempos válidos con el formato HH:MM:SS.',
      invalidTrimOrder: 'La hora de fin debe ser posterior a la de inicio.',
      dropFile: 'Suelta tu archivo aquí',
      orBrowse: 'o',
      clickBrowse: 'haz clic para buscar',
      supports: 'Compatible con: {supported} - Máx 200 MB',
      ready: 'Listo para procesar',
      uploading: 'Subiendo...',
      ownership: 'Al subir un archivo, confirmas que eres propietario del contenido o que tienes permiso para procesarlo.',
      processAnother: 'Procesar otro archivo',
      startingJob: 'Iniciando proceso...',
      processing: 'Procesando tu archivo...',
      failed: 'El procesamiento falló. Inténtalo de nuevo.',
      complete: '¡Conversión completada!',
      download: 'Descargar archivo',
      availableUntil: 'Archivo disponible hasta {time} (eliminación automática tras 2h)',
      uploadFailed: 'Error al subir el archivo',
      statusFailed: 'No se pudo obtener el estado del proceso',
    },
  },
} satisfies Record<Locale, unknown>;

export function getCopy(locale: Locale) {
  return COMMON_COPY[locale];
}
