import type { IconName } from '@/components/SiteIcon';
import type { Locale } from './i18n';

export interface ToolOption {
  key: string;
  label: string;
  type: 'select' | 'time';
  options?: { value: string; label: string }[];
  defaultValue?: string;
}

export interface Tool {
  slug: string;
  title: string;
  h1: string;
  description: string;
  metaTitle: string;
  metaDescription: string;
  icon: IconName;
  accepts: string[];
  outputFormat: string;
  toolType: string;
  actionLabel: string;
  outputNote: string;
  useCases: string[];
  options?: ToolOption[];
  related: string[];
  faq: { q: string; a: string }[];
  howTo: string[];
  intro: string;
  category: 'video' | 'audio' | 'converter' | 'compressor' | 'ai';
}

const EN_TOOLS: Tool[] = [
  {
    slug: 'download-video',
    title: 'Video Downloader',
    h1: 'Online Video Downloader',
    description: 'Download videos and audio from YouTube, TikTok, Twitter, Instagram and 1000+ sites.',
    metaTitle: 'Video Downloader Online - Free | OnlineMediaTools',
    metaDescription: 'Free online video downloader — no signup required. Download MP4 video or MP3 audio from YouTube, TikTok, Instagram, Twitter/X, Vimeo and 1000+ sites.',
    icon: 'videoCategory',
    accepts: ['.url'],
    outputFormat: 'mp4',
    toolType: 'download-url',
    actionLabel: 'Download',
    outputNote: 'Video downloaded as MP4 up to 480p. Audio extracted as MP3.',
    useCases: [
      'Download YouTube videos for offline viewing.',
      'Extract audio from any video as MP3.',
      'Download TikTok, Instagram Reels or Twitter videos.',
      'Save Vimeo or Dailymotion videos.',
    ],
    related: ['mp4-to-mp3', 'extract-audio', 'transcribe-audio', 'compress-video'],
    intro: 'Download video or audio from YouTube, TikTok, Twitter/X, Instagram, Vimeo and 1000+ other platforms.',
    howTo: [
      'Copy the video URL from YouTube, TikTok, or any supported site',
      'Paste it in the URL field',
      'Choose Video (MP4) or Audio (MP3)',
      'Click Download and wait',
      'Save your file',
    ],
    faq: [
      { q: 'Which sites are supported?', a: 'YouTube, TikTok, Twitter/X, Instagram, Vimeo, Dailymotion, Facebook, Reddit, Twitch and 1000+ other sites powered by yt-dlp.' },
      { q: 'What quality is the video?', a: 'Videos are downloaded at up to 480p MP4 to ensure fast cloud processing. For higher quality, use a local tool.' },
      { q: 'Can I download audio only?', a: 'Yes. Select "Audio (MP3)" to extract just the audio track as an MP3 file.' },
      { q: 'Is it free? Do I need an account?', a: 'Yes, completely free. No signup or account required.' },
      { q: 'How long are files kept?', a: 'Downloaded files are automatically deleted after 30 minutes for privacy and storage reasons.' },
      { q: 'Is it legal to download videos?', a: 'Only download content you own or have explicit permission to download. Downloading copyrighted content without permission may violate platform terms of service.' },
      { q: 'Can I download YouTube videos?', a: 'Yes, YouTube is supported. Paste the YouTube URL and choose Video (MP4) or Audio (MP3).' },
    ],
    category: 'video',
  },
  {
    slug: 'webm-to-mp4',
    title: 'WebM to MP4',
    h1: 'WebM to MP4 Converter',
    description: 'Convert WebM videos to MP4 online for free.',
    metaTitle: 'WebM to MP4 Converter Online - Free & Fast',
    metaDescription: 'Convert WebM videos to MP4 online for free. Upload your WebM file, convert it securely, and download your MP4. Files are automatically deleted after 2 hours.',
    icon: 'webmToMp4',
    accepts: ['.webm'],
    outputFormat: 'mp4',
    toolType: 'webm_to_mp4',
    actionLabel: 'Convert Now',
    outputNote: 'Your uploaded WebM file is converted into MP4 for broader compatibility with phones, laptops, messaging apps, and editing software.',
    useCases: [
      'Make browser recordings easier to play on Apple and Windows devices.',
      'Convert WebM files before sharing them in presentations or chat apps.',
      'Prepare captured meetings or screen recordings for broader upload support.',
    ],
    related: ['mov-to-mp4', 'video-converter', 'compress-video', 'mp4-to-mp3'],
    intro: 'Convert your WebM videos to the universally compatible MP4 format. Our free online tool handles the conversion securely in the cloud with no software installation required.',
    howTo: ['Upload your .webm file by dragging it or clicking the upload area', 'Click "Convert Now" to start the process', 'Wait a few seconds for processing to complete', 'Download your converted MP4 file'],
    faq: [
      { q: 'Is WebM to MP4 conversion free?', a: 'Yes, completely free. No sign-up required.' },
      { q: 'How long does conversion take?', a: 'Most files convert in under a minute depending on size.' },
      { q: 'Are my files kept private?', a: 'Yes. Files are automatically deleted after 2 hours.' },
      { q: 'What is the max file size?', a: 'Up to 200 MB per file.' },
    ],
    category: 'converter',
  },
  {
    slug: 'mov-to-mp4',
    title: 'MOV to MP4',
    h1: 'MOV to MP4 Converter',
    description: 'Convert Apple MOV videos to MP4 online for free.',
    metaTitle: 'MOV to MP4 Converter Online - Free & Fast',
    metaDescription: 'Convert MOV files to MP4 online for free. Works with iPhone and Mac videos. Secure upload, fast conversion, auto-deleted after 2 hours.',
    icon: 'movToMp4',
    accepts: ['.mov'],
    outputFormat: 'mp4',
    toolType: 'mov_to_mp4',
    actionLabel: 'Convert Now',
    outputNote: 'MOV files are re-encoded to MP4 so they are easier to upload, edit, and play outside the Apple ecosystem.',
    useCases: [
      'Convert iPhone or Mac camera files into a more portable video format.',
      'Prepare MOV clips for websites and apps that expect MP4 uploads.',
      'Make Apple-originated files easier to work with across devices.',
    ],
    related: ['webm-to-mp4', 'video-converter', 'compress-video', 'mp4-to-mp3'],
    intro: 'Convert your MOV files from iPhone, iPad, or Mac to MP4 format that works on nearly any device. Fast, free, and no account needed.',
    howTo: ['Upload your .mov file', 'Click "Convert Now"', 'Download your MP4 file'],
    faq: [
      { q: 'Can I convert iPhone videos?', a: 'Yes, MOV is the default iPhone video format and converts well.' },
      { q: 'Will I lose quality?', a: 'Only minimal quality loss is expected with standard H.264 encoding settings.' },
    ],
    category: 'converter',
  },
  {
    slug: 'mp4-to-mp3',
    title: 'MP4 to MP3',
    h1: 'MP4 to MP3 Converter',
    description: 'Extract MP3 audio from MP4 video files online for free.',
    metaTitle: 'MP4 to MP3 Converter Online - Extract Audio Free',
    metaDescription: 'Convert MP4 to MP3 online for free. Extract high-quality audio from any MP4 video. No software needed, files deleted after 2 hours.',
    icon: 'mp4ToMp3',
    accepts: ['.mp4', '.m4v'],
    outputFormat: 'mp3',
    toolType: 'mp4_to_mp3',
    actionLabel: 'Extract Audio',
    outputNote: 'The audio track is exported as MP3 so you can save spoken content, music, or interviews as a lighter standalone file.',
    useCases: [
      'Save lectures, podcasts, or interviews from MP4 video files.',
      'Extract background audio for offline listening on mobile devices.',
      'Create audio-only versions of webinars or recorded presentations.',
    ],
    options: [{ key: 'bitrate', label: 'Audio Quality', type: 'select', options: [{ value: '128k', label: '128 kbps' }, { value: '192k', label: '192 kbps (Recommended)' }, { value: '320k', label: '320 kbps (High)' }], defaultValue: '192k' }],
    related: ['video-to-mp3', 'extract-audio', 'audio-converter', 'remove-audio-from-video'],
    intro: 'Extract audio from any MP4 video and save it as an MP3 file. It is useful for music, lectures, interviews, and podcasts.',
    howTo: ['Upload your MP4 file', 'Choose audio quality (optional)', 'Click "Extract Audio"', 'Download your MP3 file'],
    faq: [
      { q: 'What bitrate will the MP3 be?', a: 'Default is 192 kbps. You can choose 128, 192, or 320 kbps.' },
      { q: 'Does this work with any MP4 file?', a: 'Yes, as long as the MP4 contains an audio track.' },
    ],
    category: 'audio',
  },
  {
    slug: 'video-to-mp3',
    title: 'Video to MP3',
    h1: 'Video to MP3 Converter',
    description: 'Convert any video file to MP3 audio online for free.',
    metaTitle: 'Video to MP3 Converter Online - Free Audio Extractor',
    metaDescription: 'Convert video to MP3 online for free. Supports MP4, WebM, MOV, AVI, MKV. Fast, secure, and files auto-deleted after 2 hours.',
    icon: 'videoToMp3',
    accepts: ['.mp4', '.webm', '.mov', '.avi', '.mkv', '.flv'],
    outputFormat: 'mp3',
    toolType: 'video_to_mp3',
    actionLabel: 'Convert to MP3',
    outputNote: 'This tool converts the audio from several major video formats into a standard MP3 file that is easy to play on most devices.',
    useCases: [
      'Turn video interviews or webinars into audio you can listen to later.',
      'Extract the soundtrack from recordings in formats beyond MP4.',
      'Create portable MP3 files from mixed video sources with one workflow.',
    ],
    related: ['mp4-to-mp3', 'extract-audio', 'audio-converter', 'remove-audio-from-video'],
    intro: 'Extract audio from common video formats and get an MP3 file instantly. It works with MP4, WebM, MOV, AVI, MKV, and more.',
    howTo: ['Upload any video file', 'Click "Convert to MP3"', 'Download your MP3 audio'],
    faq: [{ q: 'Which video formats are supported?', a: 'MP4, WebM, MOV, AVI, MKV, FLV, and similar common video formats are supported.' }],
    category: 'audio',
  },
  {
    slug: 'compress-video',
    title: 'Compress Video',
    h1: 'Compress Video Online',
    description: 'Reduce video file size online without losing too much quality.',
    metaTitle: 'Compress Video Online - Reduce File Size Free',
    metaDescription: 'Compress video online free — no watermark, no signup. Reduce MP4, MOV, WebM file size by up to 70%. Choose quality level. Auto-deleted after 2 hours.',
    icon: 'compressVideo',
    accepts: ['.mp4', '.webm', '.mov', '.avi', '.mkv'],
    outputFormat: 'mp4',
    toolType: 'compress_video',
    actionLabel: 'Compress Video',
    outputNote: 'Compression reduces file size for easier sharing and storage while preserving as much visual quality as possible for the selected level.',
    useCases: [
      'Shrink videos before uploading them to forms, email, or WhatsApp.',
      'Reduce storage usage for screen recordings and long clips.',
      'Prepare large files for quicker downloads and faster transfers.',
      'Compress videos for social media upload (Instagram, TikTok, Twitter/X).',
      'Reduce video file size before attaching to email or sharing via link.',
    ],
    options: [{ key: 'quality', label: 'Quality Level', type: 'select', options: [{ value: 'high_quality', label: 'High Quality (larger file)' }, { value: 'balanced', label: 'Balanced (recommended)' }, { value: 'small_size', label: 'Small Size (lower quality)' }], defaultValue: 'balanced' }],
    related: ['video-converter', 'webm-to-mp4', 'trim-video', 'remove-audio-from-video'],
    intro: 'Reduce your video file size online — no watermark, no signup, no software to install. Upload your MP4, MOV, or WebM, choose a compression level, and download a smaller file in seconds. Free to use with automatic file deletion after 2 hours.',
    howTo: ['Upload your video file', 'Select compression quality', 'Click "Compress Video"', 'Download the compressed file'],
    faq: [
      { q: 'How much will it reduce the file size?', a: 'Typical reduction ranges from 30% to 70%, depending on the source file and the quality level chosen.' },
      { q: 'Is there a watermark on the compressed video?', a: 'No. There is no watermark added to your video. The output is a clean MP4 file.' },
      { q: 'Do I need to create an account?', a: 'No signup or account is required. Just upload and compress your video instantly.' },
      { q: 'What video formats can I compress?', a: 'You can upload MP4, WebM, MOV, AVI, and MKV files for compression.' },
      { q: 'How long are files stored?', a: 'All uploaded and processed files are automatically deleted after 2 hours.' },
      { q: 'What is the maximum file size?', a: 'You can upload video files up to 200 MB.' },
    ],
    category: 'compressor',
  },
  {
    slug: 'extract-audio',
    title: 'Extract Audio',
    h1: 'Extract Audio from Video',
    description: 'Extract audio from any video file and download as MP3, WAV, or AAC.',
    metaTitle: 'Extract Audio from Video Online Free',
    metaDescription: 'Extract audio from video files online. Save as MP3, WAV, or AAC. Supports all major video formats. Free, no signup, files deleted after 2 hours.',
    icon: 'extractAudio',
    accepts: ['.mp4', '.webm', '.mov', '.avi', '.mkv'],
    outputFormat: 'mp3',
    toolType: 'extract_audio',
    actionLabel: 'Extract Audio',
    outputNote: 'You can export the audio track as MP3, WAV, or AAC depending on whether you want compatibility, lossless quality, or a compact file.',
    useCases: [
      'Save the spoken audio from tutorials, classes, or demos.',
      'Export clean WAV or AAC tracks for editing or reuse.',
      'Separate voice or music from a video without desktop software.',
    ],
    options: [{ key: 'fmt', label: 'Output Format', type: 'select', options: [{ value: 'mp3', label: 'MP3' }, { value: 'wav', label: 'WAV' }, { value: 'aac', label: 'AAC' }], defaultValue: 'mp3' }],
    related: ['mp4-to-mp3', 'video-to-mp3', 'audio-converter', 'remove-audio-from-video'],
    intro: 'Pull the audio track out of a video and save it in your preferred format. MP3, WAV, and AAC output are supported.',
    howTo: ['Upload your video file', 'Choose output audio format', 'Click "Extract Audio"', 'Download your audio file'],
    faq: [{ q: 'Which audio formats can I export?', a: 'MP3, WAV, and AAC are supported.' }],
    category: 'audio',
  },
  {
    slug: 'remove-audio-from-video',
    title: 'Remove Audio from Video',
    h1: 'Remove Audio from Video',
    description: 'Strip the audio track from a video file online for free.',
    metaTitle: 'Remove Audio from Video Online Free',
    metaDescription: 'Remove audio from video online for free. Create silent videos by stripping the audio track. Fast processing, files deleted after 2 hours.',
    icon: 'removeAudio',
    accepts: ['.mp4', '.webm', '.mov', '.avi', '.mkv'],
    outputFormat: 'mp4',
    toolType: 'remove_audio',
    actionLabel: 'Remove Audio',
    outputNote: 'The tool outputs a silent MP4 video so you can reuse footage without its original soundtrack or spoken audio.',
    useCases: [
      'Mute videos before reusing them in presentations or social edits.',
      'Remove sensitive spoken audio while keeping the video stream intact.',
      'Create silent clips for overlays, captions, or replacement music.',
    ],
    related: ['extract-audio', 'compress-video', 'video-converter', 'trim-video'],
    intro: 'Remove the audio track from a video to create a silent file. It is useful for privacy, remixing, captions, and replacement soundtracks.',
    howTo: ['Upload your video', 'Click "Remove Audio"', 'Download the silent video'],
    faq: [{ q: 'Will the video quality change?', a: 'The video stream is typically copied directly, so visual quality stays the same in most cases.' }],
    category: 'video',
  },
  {
    slug: 'audio-converter',
    title: 'Audio Converter',
    h1: 'Online Audio Converter',
    description: 'Convert audio files between MP3, WAV, AAC, OGG, and FLAC online.',
    metaTitle: 'Audio Converter Online - MP3, WAV, AAC, OGG, FLAC',
    metaDescription: 'Convert audio files online for free. Supports MP3, WAV, AAC, OGG, FLAC. Fast, secure conversion with auto-delete after 2 hours.',
    icon: 'audioConverter',
    accepts: ['.mp3', '.wav', '.aac', '.ogg', '.flac', '.m4a'],
    outputFormat: 'mp3',
    toolType: 'audio_converter',
    actionLabel: 'Convert Audio',
    outputNote: 'Choose the output format that matches your playback, editing, archiving, or sharing needs from the major audio standards.',
    useCases: [
      'Convert recordings into a format supported by your playback device.',
      'Create lighter MP3 files or preserve detail with FLAC or WAV.',
      'Standardize mixed audio files before publishing or editing them.',
    ],
    options: [{ key: 'target_fmt', label: 'Output Format', type: 'select', options: [{ value: 'mp3', label: 'MP3' }, { value: 'wav', label: 'WAV' }, { value: 'aac', label: 'AAC' }, { value: 'ogg', label: 'OGG' }, { value: 'flac', label: 'FLAC' }], defaultValue: 'mp3' }],
    related: ['extract-audio', 'mp4-to-mp3', 'video-to-mp3', 'remove-audio-from-video'],
    intro: 'Convert between major audio formats online. Upload a file, choose the target format, and download the converted result.',
    howTo: ['Upload your audio file', 'Choose the output format', 'Click "Convert Audio"', 'Download the converted audio'],
    faq: [{ q: 'Which audio formats are supported?', a: 'MP3, WAV, AAC, OGG, FLAC, and similar common audio formats are supported.' }],
    category: 'converter',
  },
  {
    slug: 'video-converter',
    title: 'Video Converter',
    h1: 'Online Video Converter',
    description: 'Convert video files between WebM, MOV, AVI, MKV, and MP4 online.',
    metaTitle: 'Video Converter Online - MP4, WebM, MOV, AVI, MKV',
    metaDescription: 'Convert video files online for free. Supports MP4, WebM, MOV, AVI, MKV formats. Secure and fast, files deleted after 2 hours.',
    icon: 'videoConverter',
    accepts: ['.mp4', '.webm', '.mov', '.avi', '.mkv'],
    outputFormat: 'mp4',
    toolType: 'video_converter',
    actionLabel: 'Convert Video',
    outputNote: 'You can convert common video formats into the output you need for playback, uploads, or downstream editing workflows.',
    useCases: [
      'Change video containers before uploading to websites or apps.',
      'Standardize clips from different sources into one format.',
      'Create MP4 or WebM versions for compatibility and delivery needs.',
    ],
    options: [{ key: 'target_fmt', label: 'Output Format', type: 'select', options: [{ value: 'mp4', label: 'MP4' }, { value: 'webm', label: 'WebM' }], defaultValue: 'mp4' }],
    related: ['webm-to-mp4', 'mov-to-mp4', 'compress-video', 'trim-video'],
    intro: 'Convert common video formats into the one you need. The tool handles MP4, WebM, MOV, AVI, and MKV inputs.',
    howTo: ['Upload your video', 'Choose output format', 'Click "Convert Video"', 'Download your video'],
    faq: [{ q: 'Which video formats are supported?', a: 'MP4, WebM, MOV, AVI, MKV, and related common formats are supported.' }],
    category: 'converter',
  },
  {
    slug: 'trim-video',
    title: 'Trim Video',
    h1: 'Trim Video Online',
    description: 'Cut and trim video files online for free. Set start and end time.',
    metaTitle: 'Trim Video Online Free - Cut Video by Time',
    metaDescription: 'Trim and cut video online for free. Set start and end times to extract the clip you need. Fast, secure, files deleted after 2 hours.',
    icon: 'trimVideo',
    accepts: ['.mp4', '.webm', '.mov', '.avi', '.mkv'],
    outputFormat: 'mp4',
    toolType: 'trim_video',
    actionLabel: 'Trim Video',
    outputNote: 'The output clip keeps only the section between your chosen start and end times, which is useful for highlights and shorter edits.',
    useCases: [
      'Cut out dead space, mistakes, or long pauses from recordings.',
      'Create short highlight clips for sharing or embedding.',
      'Prepare a smaller excerpt before converting or compressing a video.',
    ],
    options: [
      { key: 'start', label: 'Start Time (HH:MM:SS)', type: 'time', defaultValue: '00:00:00' },
      { key: 'end', label: 'End Time (HH:MM:SS)', type: 'time', defaultValue: '00:01:00' },
    ],
    related: ['compress-video', 'remove-audio-from-video', 'video-converter', 'extract-audio'],
    intro: 'Trim your video to the exact clip you need by setting a start and end time. It is useful for highlights, excerpts, and quick cleanups.',
    howTo: ['Upload your video', 'Enter start and end times', 'Click "Trim Video"', 'Download your trimmed clip'],
    faq: [{ q: 'What time format should I use?', a: 'Use HH:MM:SS format, for example 00:01:30 for 1 minute 30 seconds.' }],
    category: 'video',
  },
  {
    slug: 'transcribe-audio',
    title: 'Transcribe Audio to Text',
    h1: 'Transcribe Audio to Text Online',
    description: 'AI transcription for audio and video files online.',
    metaTitle: 'Transcribe Audio to Text Online - Free AI Transcription',
    metaDescription: 'Free AI audio transcription online — no signup required. Convert MP3, MP4, WAV, M4A, MOV or WebM to text. Powered by Whisper AI. Export TXT or SRT.',
    icon: 'transcribeAudio',
    accepts: ['.mp3', '.mp4', '.wav', '.m4a', '.mov', '.webm'],
    outputFormat: 'txt',
    toolType: 'transcribe',
    actionLabel: 'Transcribe Audio',
    outputNote: 'Use this tool when you need a fast first-pass transcript, interview notes, meeting text, or subtitle draft from an audio or video file.',
    useCases: [
      'Transcribe podcast episodes for show notes or blog posts.',
      'Convert interview recordings to editable text for journalism.',
      'Generate meeting and webinar transcripts automatically.',
      'Create a first-pass draft before manual subtitle editing.',
      'Transcribe lectures and educational audio for accessibility.',
      'Convert voice memos or audio notes to searchable text.',
    ],
    options: [
      { key: 'format', label: 'Output Format', type: 'select', options: [{ value: 'txt', label: 'TXT' }, { value: 'srt', label: 'SRT' }], defaultValue: 'txt' }
    ],
    related: ['auto-subtitle', 'translate-subtitles', 'clean-audio', 'extract-audio'],
    faq: [
      { q: 'Which output formats are available?', a: 'You can export the result as TXT for readable text or SRT for subtitle-ready timing.' },
      { q: 'Can I upload video files too?', a: 'Yes. You can transcribe MP4, MOV, WebM and other video uploads with the same workflow — the audio is extracted automatically.' },
      { q: 'When should I choose TXT instead of SRT?', a: 'Choose TXT for notes, summaries, and copy editing. Choose SRT when you want subtitle timing that can be imported into video platforms.' },
      { q: 'Is this tool powered by Whisper AI?', a: 'Yes. The transcription engine is based on OpenAI Whisper, a state-of-the-art speech recognition model that supports 90+ languages.' },
      { q: 'Is it free? Do I need to sign up?', a: 'Yes, completely free. No account or signup required. Just upload your file and download your transcript.' },
      { q: 'How accurate is the transcription?', a: 'Accuracy depends on audio quality and clarity. For clean speech recordings, accuracy is typically above 90%. Background noise can reduce accuracy.' },
      { q: 'What languages are supported?', a: 'The Whisper AI model supports over 90 languages including English, French, Spanish, German, Arabic, Portuguese, and more.' },
      { q: 'How long does transcription take?', a: 'Most files are processed in 1–3 minutes depending on length. A 30-minute audio file typically takes 1–2 minutes.' },
    ],
    howTo: ['Upload your audio or video file', 'Choose TXT or SRT output', 'Click "Transcribe Audio"', 'Download the transcript file'],
    intro: 'Upload an audio or video file and generate an accurate AI transcript in minutes — free, no signup, powered by Whisper AI. Get clean text output for notes, summaries, or subtitles from MP3, MP4, WAV, M4A, MOV and WebM files.',
    category: 'ai'
  },
  {
    slug: 'auto-subtitle',
    title: 'Auto Subtitle Generator',
    h1: 'Generate Subtitles Automatically Online',
    description: 'Create subtitle files from audio or video with AI.',
    metaTitle: 'Auto Subtitle Generator Online - Create SRT or VTT',
    metaDescription: 'Generate subtitles automatically online with AI. Export SRT or VTT subtitle files from audio and video uploads in minutes.',
    icon: 'autoSubtitle',
    accepts: ['.mp3', '.mp4', '.wav', '.m4a', '.mov', '.webm'],
    outputFormat: 'srt',
    toolType: 'auto-subtitle',
    actionLabel: 'Generate Subtitles',
    outputNote: 'This tool is best for first-pass captions, subtitle drafts, accessibility workflows, and quick subtitle exports for editors or publishing teams.',
    useCases: [
      'Caption drafts for YouTube or social video',
      'Subtitle files for accessibility workflows',
      'Fast subtitle generation before manual review',
    ],
    options: [
      { key: 'format', label: 'Output Format', type: 'select', options: [{ value: 'srt', label: 'SRT' }, { value: 'vtt', label: 'VTT' }], defaultValue: 'srt' }
    ],
    related: ['transcribe-audio', 'translate-subtitles', 'clean-audio'],
    faq: [
      { q: 'Which subtitle formats are supported?', a: 'You can export subtitles as SRT or VTT depending on where you plan to publish or edit them.' },
      { q: 'Can I use this with audio-only files?', a: 'Yes. Supported audio-only files and standard video uploads both work.' },
      { q: 'Is this good for final subtitles?', a: 'It is ideal for a fast first draft. You should still review names, punctuation, timing, and line breaks before final publication.' },
    ],
    howTo: ['Upload your audio or video file', 'Choose SRT or VTT output', 'Click "Generate Subtitles"', 'Download the subtitle file'],
    intro: 'Generate subtitle files automatically from audio or video so you can publish captions faster and spend less time creating first drafts manually.',
    category: 'ai'
  },
  {
    slug: 'translate-subtitles',
    title: 'Translate Audio to Subtitles',
    h1: 'Translate Audio to Subtitles Online',
    description: 'Generate translated subtitle files from audio or video.',
    metaTitle: 'Translate Audio to Subtitles Online',
    metaDescription: 'Upload audio or video and generate translated subtitles online in English, French, or Spanish as SRT files.',
    icon: 'translateSubtitles',
    accepts: ['.mp3', '.mp4', '.wav', '.m4a', '.mov', '.webm'],
    outputFormat: 'srt',
    toolType: 'translate-subtitle',
    actionLabel: 'Translate Subtitles',
    outputNote: 'Use translated subtitle output for multilingual video publishing, localization pilots, audience testing, or quick regional subtitle drafts.',
    useCases: [
      'Translated subtitles for multilingual publishing',
      'Localization drafts for social or training video',
      'Quick subtitle translation for English, French, or Spanish audiences',
    ],
    options: [
      { key: 'language', label: 'Target Language', type: 'select', options: [{ value: 'en', label: 'English' }, { value: 'fr', label: 'French' }, { value: 'es', label: 'Spanish' }], defaultValue: 'fr' }
    ],
    related: ['auto-subtitle', 'transcribe-audio', 'clean-audio'],
    faq: [
      { q: 'Which target languages are available?', a: 'You can generate translated subtitles in English, French, or Spanish.' },
      { q: 'Which subtitle format is exported?', a: 'The translated result is exported as an SRT file for easy editing and publishing.' },
      { q: 'When should I use this instead of the subtitle generator?', a: 'Use this tool when your goal is subtitle translation for another audience, not just subtitle creation in the source language.' },
    ],
    howTo: ['Upload your audio or video file', 'Choose the target language', 'Click "Translate Subtitles"', 'Download the translated SRT file'],
    intro: 'Upload a file, choose the target language, and generate translated subtitles automatically for faster localization and multilingual publishing.',
    category: 'ai'
  },
  {
    slug: 'clean-audio',
    title: 'Clean Audio',
    h1: 'Clean Audio Online with AI',
    description: 'Reduce background noise from speech recordings online.',
    metaTitle: 'Clean Audio Online - AI Noise Reduction',
    metaDescription: 'Clean audio online with AI noise reduction. Remove background noise from podcasts, interviews, voice notes, and spoken video files.',
    icon: 'cleanAudio',
    accepts: ['.mp3', '.mp4', '.wav', '.m4a', '.mov', '.webm'],
    outputFormat: 'mp3',
    toolType: 'clean-audio',
    actionLabel: 'Clean Audio',
    outputNote: 'This tool is designed to reduce common background noise so speech recordings sound clearer before publishing, transcribing, subtitling, or archiving.',
    useCases: [
      'Podcast and voice-note cleanup',
      'Interview and meeting recording enhancement',
      'Prepare noisy speech files before transcription',
    ],
    related: ['extract-audio', 'transcribe-audio', 'auto-subtitle'],
    faq: [
      { q: 'Can I upload video files too?', a: 'Yes. Supported audio and video files can both be cleaned with the same workflow.' },
      { q: 'What output format will I get?', a: 'The cleaned result is exported as MP3 or MP4 depending on the source file you upload.' },
      { q: 'Should I clean audio before transcription?', a: 'Yes, especially for noisy interviews, meetings, or field recordings. Cleaner speech usually leads to better transcripts and subtitle drafts.' },
    ],
    howTo: ['Upload your audio or video file', 'Click "Clean Audio"', 'Download the cleaned result'],
    intro: 'Upload an audio or video file and remove common background noise automatically before transcription, subtitling, editing, or publishing.',
    category: 'ai'
  }
];

const FR_TOOL_TRANSLATIONS: Record<string, Partial<Tool>> = {
  'webm-to-mp4': {
    title: 'Convertir WEBM en MP4',
    h1: 'Convertir WEBM en MP4 en ligne',
    description: 'Convertir un fichier WEBM en MP4 en ligne gratuitement.',
    metaTitle: 'Convertir WEBM en MP4 en ligne - Gratuit',
    metaDescription: 'Convertir WEBM en MP4 en ligne gratuitement. Téléversez votre fichier WEBM, convertissez-le rapidement et téléchargez votre vidéo MP4. Fichiers supprimés après 2 heures.',
    actionLabel: 'Convertir maintenant',
    outputNote: 'Votre fichier WebM est converti en MP4 pour une meilleure compatibilité avec les téléphones, ordinateurs, applications de messagerie et logiciels de montage.',
    useCases: [
      'Lire plus facilement des enregistrements navigateur sur Apple et Windows.',
      'Convertir des fichiers WebM avant de les partager dans une présentation ou une messagerie.',
      'Préparer des réunions enregistrées ou captures d’écran pour des plateformes qui acceptent surtout MP4.',
    ],
    intro: 'Convertissez vos vidéos WebM vers le format MP4, largement compatible. Notre outil gratuit réalise la conversion de manière sécurisée dans le cloud, sans installation.',
    howTo: ['Envoyez votre fichier .webm par glisser-déposer ou en cliquant sur la zone d’envoi', 'Cliquez sur « Convertir maintenant » pour lancer le traitement', 'Patientez quelques secondes pendant la conversion', 'Téléchargez votre fichier MP4 converti'],
    faq: [
      { q: 'La conversion WebM vers MP4 est-elle gratuite ?', a: 'Oui, entièrement gratuite, sans inscription.' },
      { q: 'Combien de temps prend la conversion ?', a: 'La plupart des fichiers sont convertis en moins d’une minute selon leur taille.' },
      { q: 'Mes fichiers restent-ils privés ?', a: 'Oui. Les fichiers sont supprimés automatiquement après 2 heures.' },
      { q: 'Quelle est la taille maximale ?', a: 'Jusqu’à 200 Mo par fichier.' },
    ],
  },
  'mov-to-mp4': {
    title: 'Convertir MOV en MP4',
    h1: 'Convertir MOV en MP4 en ligne',
    description: 'Convertir un fichier MOV en MP4 en ligne gratuitement.',
    metaTitle: 'Convertir MOV en MP4 en ligne - Gratuit',
    metaDescription: 'Convertir MOV en MP4 en ligne gratuitement. Idéal pour les vidéos iPhone et Mac. Conversion rapide, sécurisée et suppression automatique après 2 heures.',
    actionLabel: 'Convertir maintenant',
    outputNote: 'Les fichiers MOV sont réencodés en MP4 afin d’être plus faciles à envoyer, monter et lire hors de l’écosystème Apple.',
    useCases: [
      'Convertir des vidéos iPhone ou Mac vers un format plus portable.',
      'Préparer des clips MOV pour des sites et applications qui attendent du MP4.',
      'Rendre des fichiers issus d’Apple plus simples à utiliser sur d’autres appareils.',
    ],
    intro: 'Convertissez vos fichiers MOV provenant d’iPhone, iPad ou Mac vers le format MP4, compatible avec presque tous les appareils.',
    howTo: ['Envoyez votre fichier .mov', 'Cliquez sur « Convertir maintenant »', 'Téléchargez votre fichier MP4'],
    faq: [
      { q: 'Puis-je convertir des vidéos iPhone ?', a: 'Oui. MOV est le format vidéo par défaut de l’iPhone et se convertit très bien.' },
      { q: 'Vais-je perdre en qualité ?', a: 'Une légère perte est possible selon le réencodage H.264 standard, mais elle reste généralement limitée.' },
    ],
  },
  'mp4-to-mp3': {
    title: 'Convertir MP4 en MP3',
    h1: 'Convertir MP4 en MP3 en ligne',
    description: 'Convertir MP4 en MP3 en ligne et extraire l’audio gratuitement.',
    metaTitle: 'Convertir MP4 en MP3 en ligne - Gratuit',
    metaDescription: 'Convertir MP4 en MP3 en ligne gratuitement. Extraire l’audio d’une vidéo MP4 en quelques clics, sans logiciel et avec suppression automatique après 2 heures.',
    actionLabel: 'Extraire l’audio',
    outputNote: 'La piste audio est exportée en MP3 pour enregistrer des paroles, de la musique ou des interviews sous la forme d’un fichier audio léger.',
    useCases: [
      'Enregistrer des cours, podcasts ou interviews depuis des fichiers MP4.',
      'Extraire un fond sonore à écouter hors ligne sur mobile.',
      'Créer une version audio d’un webinar ou d’une présentation enregistrée.',
    ],
    options: [{ key: 'bitrate', label: 'Qualité audio', type: 'select', options: [{ value: '128k', label: '128 kb/s' }, { value: '192k', label: '192 kb/s (Recommandé)' }, { value: '320k', label: '320 kb/s (Élevée)' }], defaultValue: '192k' }],
    intro: 'Extrayez l’audio de n’importe quelle vidéo MP4 et enregistrez-le au format MP3. Idéal pour la musique, les cours, les interviews et les podcasts.',
    howTo: ['Envoyez votre fichier MP4', 'Choisissez la qualité audio (optionnel)', 'Cliquez sur « Extraire l’audio »', 'Téléchargez votre fichier MP3'],
    faq: [
      { q: 'Quel débit binaire aura le MP3 ?', a: 'La valeur par défaut est 192 kb/s. Vous pouvez choisir 128, 192 ou 320 kb/s.' },
      { q: 'Cela fonctionne-t-il avec n’importe quel MP4 ?', a: 'Oui, tant que le fichier MP4 contient une piste audio.' },
    ],
  },
  'video-to-mp3': {
    title: 'Convertir vidéo en MP3',
    h1: 'Convertir une vidéo en MP3 en ligne',
    description: 'Convertir une vidéo en MP3 en ligne gratuitement.',
    metaTitle: 'Convertir une vidéo en MP3 en ligne - Gratuit',
    metaDescription: 'Convertir une vidéo en MP3 en ligne gratuitement. Compatible avec MP4, WebM, MOV, AVI et MKV. Rapide, sécurisé et suppression auto après 2 heures.',
    actionLabel: 'Convertir en MP3',
    outputNote: 'Cet outil convertit l’audio de plusieurs grands formats vidéo vers un fichier MP3 standard facile à lire sur la plupart des appareils.',
    useCases: [
      'Transformer des interviews vidéo ou webinars en audio à écouter plus tard.',
      'Extraire la bande-son d’enregistrements dans des formats autres que MP4.',
      'Créer des fichiers MP3 portables à partir de sources vidéo variées.',
    ],
    intro: 'Extrayez l’audio des formats vidéo courants et obtenez instantanément un fichier MP3. Compatible avec MP4, WebM, MOV, AVI, MKV et plus.',
    howTo: ['Envoyez n’importe quel fichier vidéo', 'Cliquez sur « Convertir en MP3 »', 'Téléchargez votre fichier MP3'],
    faq: [{ q: 'Quels formats vidéo sont pris en charge ?', a: 'MP4, WebM, MOV, AVI, MKV, FLV et d’autres formats vidéo courants sont pris en charge.' }],
  },
  'compress-video': {
    title: 'Compresser une vidéo',
    h1: 'Compresser une vidéo en ligne',
    description: 'Compresser une vidéo en ligne et réduire sa taille gratuitement.',
    metaTitle: 'Compresser une vidéo en ligne - Gratuit',
    metaDescription: 'Compresser une vidéo en ligne gratuitement et réduire la taille du fichier pour e-mail, upload ou stockage. Choisissez votre qualité. Fichiers supprimés après 2 heures.',
    actionLabel: 'Compresser la vidéo',
    outputNote: 'La compression réduit la taille du fichier pour faciliter le partage et le stockage tout en conservant le plus de qualité visuelle possible selon le niveau choisi.',
    useCases: [
      'Réduire la taille de vidéos avant un envoi par formulaire, e-mail ou messagerie.',
      'Diminuer l’espace de stockage utilisé par des captures ou de longs clips.',
      'Préparer de gros fichiers pour des téléchargements et transferts plus rapides.',
    ],
    options: [{ key: 'quality', label: 'Niveau de qualité', type: 'select', options: [{ value: 'high_quality', label: 'Haute qualité (fichier plus volumineux)' }, { value: 'balanced', label: 'Équilibré (recommandé)' }, { value: 'small_size', label: 'Petite taille (qualité réduite)' }], defaultValue: 'balanced' }],
    intro: 'Réduisez la taille d’une vidéo en ligne sans réglages compliqués. Choisissez un niveau de qualité et laissez l’outil faire la compression.',
    howTo: ['Envoyez votre fichier vidéo', 'Sélectionnez le niveau de compression', 'Cliquez sur « Compresser la vidéo »', 'Téléchargez le fichier compressé'],
    faq: [{ q: 'De combien la taille peut-elle être réduite ?', a: 'La réduction typique va de 30 % à 70 % selon le fichier source et le niveau choisi.' }],
  },
  'extract-audio': {
    title: 'Extraire l’audio d’une vidéo',
    h1: 'Extraire l’audio d’une vidéo en ligne',
    description: 'Extraire l’audio d’une vidéo en ligne en MP3, WAV ou AAC.',
    metaTitle: 'Extraire l’audio d’une vidéo en ligne - Gratuit',
    metaDescription: 'Extraire l’audio d’une vidéo en ligne gratuitement. Exportez votre fichier en MP3, WAV ou AAC. Compatible avec les principaux formats vidéo.',
    actionLabel: 'Extraire l’audio',
    outputNote: 'Vous pouvez exporter la piste audio en MP3, WAV ou AAC selon que vous recherchiez la compatibilité, une qualité sans perte ou un fichier compact.',
    useCases: [
      'Enregistrer la parole de tutoriels, cours ou démonstrations.',
      'Exporter des pistes WAV ou AAC propres pour montage ou réutilisation.',
      'Séparer voix ou musique d’une vidéo sans logiciel desktop.',
    ],
    options: [{ key: 'fmt', label: 'Format de sortie', type: 'select', options: [{ value: 'mp3', label: 'MP3' }, { value: 'wav', label: 'WAV' }, { value: 'aac', label: 'AAC' }], defaultValue: 'mp3' }],
    intro: 'Récupérez la piste audio d’une vidéo et enregistrez-la dans le format souhaité. Sorties MP3, WAV et AAC disponibles.',
    howTo: ['Envoyez votre fichier vidéo', 'Choisissez le format audio de sortie', 'Cliquez sur « Extraire l’audio »', 'Téléchargez votre fichier audio'],
    faq: [{ q: 'Quels formats audio puis-je exporter ?', a: 'Les formats MP3, WAV et AAC sont disponibles.' }],
  },
  'remove-audio-from-video': {
    title: 'Supprimer l’audio d’une vidéo',
    h1: 'Supprimer l’audio d’une vidéo en ligne',
    description: 'Supprimer l’audio d’une vidéo en ligne gratuitement.',
    metaTitle: 'Supprimer l’audio d’une vidéo en ligne - Gratuit',
    metaDescription: 'Supprimer l’audio d’une vidéo en ligne gratuitement et créer une vidéo muette en quelques clics. Traitement rapide et suppression après 2 heures.',
    actionLabel: 'Supprimer l’audio',
    outputNote: 'L’outil produit une vidéo MP4 muette afin de réutiliser vos images sans bande-son ou sans voix d’origine.',
    useCases: [
      'Mettre une vidéo en muet avant de la réutiliser dans une présentation ou un montage social.',
      'Retirer une parole sensible tout en conservant l’image intacte.',
      'Créer un clip muet pour sous-titres, superpositions ou musique de remplacement.',
    ],
    intro: 'Retirez la piste audio d’une vidéo pour créer un fichier muet. Utile pour la confidentialité, le remix, les sous-titres ou un nouveau fond sonore.',
    howTo: ['Envoyez votre vidéo', 'Cliquez sur « Supprimer l’audio »', 'Téléchargez la vidéo muette'],
    faq: [{ q: 'La qualité vidéo va-t-elle changer ?', a: 'Le flux vidéo est généralement copié tel quel, donc la qualité visuelle reste identique dans la plupart des cas.' }],
  },
  'audio-converter': {
    title: 'Convertisseur audio',
    h1: 'Convertisseur audio en ligne',
    description: 'Convertir des fichiers audio en ligne entre MP3, WAV, AAC, OGG et FLAC.',
    metaTitle: 'Convertisseur audio en ligne - Gratuit',
    metaDescription: 'Convertisseur audio en ligne gratuit pour MP3, WAV, AAC, OGG et FLAC. Conversion rapide, sécurisée et suppression automatique après 2 heures.',
    actionLabel: 'Convertir l’audio',
    outputNote: 'Choisissez le format de sortie adapté à la lecture, au montage, à l’archivage ou au partage parmi les principaux standards audio.',
    useCases: [
      'Convertir des enregistrements vers un format pris en charge par votre appareil.',
      'Créer des MP3 plus légers ou conserver plus de détails avec FLAC ou WAV.',
      'Uniformiser des fichiers audio variés avant publication ou montage.',
    ],
    options: [{ key: 'target_fmt', label: 'Format de sortie', type: 'select', options: [{ value: 'mp3', label: 'MP3' }, { value: 'wav', label: 'WAV' }, { value: 'aac', label: 'AAC' }, { value: 'ogg', label: 'OGG' }, { value: 'flac', label: 'FLAC' }], defaultValue: 'mp3' }],
    intro: 'Convertissez entre les principaux formats audio en ligne. Envoyez un fichier, choisissez le format cible, puis téléchargez le résultat.',
    howTo: ['Envoyez votre fichier audio', 'Choisissez le format de sortie', 'Cliquez sur « Convertir l’audio »', 'Téléchargez votre fichier converti'],
    faq: [{ q: 'Quels formats audio sont pris en charge ?', a: 'MP3, WAV, AAC, OGG, FLAC et d’autres formats audio courants sont pris en charge.' }],
  },
  'video-converter': {
    title: 'Convertisseur vidéo',
    h1: 'Convertisseur vidéo en ligne',
    description: 'Convertir des fichiers vidéo en ligne entre MP4, WebM, MOV, AVI et MKV.',
    metaTitle: 'Convertisseur vidéo en ligne - Gratuit',
    metaDescription: 'Convertisseur vidéo en ligne gratuit pour MP4, WebM, MOV, AVI et MKV. Conversion rapide, sécurisée et suppression automatique après 2 heures.',
    actionLabel: 'Convertir la vidéo',
    outputNote: 'Vous pouvez convertir les formats vidéo courants vers le format de sortie nécessaire pour la lecture, l’envoi ou le montage.',
    useCases: [
      'Changer de conteneur vidéo avant un envoi vers un site ou une application.',
      'Uniformiser des clips provenant de différentes sources.',
      'Créer des versions MP4 ou WebM selon vos besoins de compatibilité.',
    ],
    options: [{ key: 'target_fmt', label: 'Format de sortie', type: 'select', options: [{ value: 'mp4', label: 'MP4' }, { value: 'webm', label: 'WebM' }], defaultValue: 'mp4' }],
    intro: 'Convertissez les formats vidéo les plus courants vers celui dont vous avez besoin. L’outil gère les entrées MP4, WebM, MOV, AVI et MKV.',
    howTo: ['Envoyez votre vidéo', 'Choisissez le format de sortie', 'Cliquez sur « Convertir la vidéo »', 'Téléchargez votre vidéo'],
    faq: [{ q: 'Quels formats vidéo sont pris en charge ?', a: 'Les formats MP4, WebM, MOV, AVI, MKV et d’autres formats vidéo courants sont pris en charge.' }],
  },
  'trim-video': {
    title: 'Couper une vidéo',
    h1: 'Couper une vidéo en ligne',
    description: 'Couper et recadrer une vidéo en ligne gratuitement.',
    metaTitle: 'Couper une vidéo en ligne - Gratuit',
    metaDescription: 'Couper une vidéo en ligne gratuitement. Définissez l’heure de début et de fin pour extraire le clip voulu. Rapide, sécurisé et suppression après 2 heures.',
    actionLabel: 'Couper la vidéo',
    outputNote: 'Le clip de sortie ne conserve que la portion comprise entre l’heure de début et l’heure de fin choisies, idéal pour les extraits et moments forts.',
    useCases: [
      'Supprimer les blancs, erreurs ou longues pauses dans un enregistrement.',
      'Créer de courts extraits à partager ou intégrer.',
      'Préparer un passage plus court avant conversion ou compression.',
    ],
    options: [
      { key: 'start', label: 'Heure de début (HH:MM:SS)', type: 'time', defaultValue: '00:00:00' },
      { key: 'end', label: 'Heure de fin (HH:MM:SS)', type: 'time', defaultValue: '00:01:00' },
    ],
    intro: 'Coupez votre vidéo exactement au passage voulu en définissant une heure de début et de fin. Pratique pour les extraits, résumés et nettoyages rapides.',
    howTo: ['Envoyez votre vidéo', 'Saisissez l’heure de début et de fin', 'Cliquez sur « Couper la vidéo »', 'Téléchargez votre extrait'],
    faq: [{ q: 'Quel format d’heure dois-je utiliser ?', a: 'Utilisez le format HH:MM:SS, par exemple 00:01:30 pour 1 minute et 30 secondes.' }],
  },
  'transcribe-audio': {
    title: 'Transcrire un audio en texte',
    h1: 'Transcrire un audio en texte en ligne',
    description: 'Transcription IA pour fichiers audio et vidéo.',
    metaTitle: 'Transcrire un audio en texte en ligne - IA gratuite',
    metaDescription: 'Transcrivez un audio ou une vidéo en texte en ligne avec l’IA. Export TXT ou SRT depuis MP3, MP4, WAV, MOV, M4A et WebM.',
    actionLabel: 'Transcrire l’audio',
    outputNote: 'Cet outil convient aux comptes rendus, notes d’interview, brouillons de sous-titres et premières versions de transcription à retravailler.',
    useCases: ['Comptes rendus de réunion et webinar', 'Transcriptions d’interviews', 'Brouillons avant édition de sous-titres'],
    options: [{ key: 'format', label: 'Format de sortie', type: 'select', options: [{ value: 'txt', label: 'TXT' }, { value: 'srt', label: 'SRT' }], defaultValue: 'txt' }],
    related: ['auto-subtitle', 'translate-subtitles', 'clean-audio', 'extract-audio'],
    faq: [
      { q: 'Quels formats de sortie sont disponibles ?', a: 'Vous pouvez exporter le résultat en TXT pour un texte lisible ou en SRT pour un format prêt à sous-titrer.' },
      { q: 'Puis-je envoyer une vidéo ?', a: 'Oui. Les fichiers audio et vidéo pris en charge peuvent être transcrits avec le même workflow.' },
      { q: 'Quand choisir TXT plutôt que SRT ?', a: 'Choisissez TXT pour les notes, résumés et retouches de texte. Choisissez SRT si vous avez besoin d’un fichier importable dans un outil vidéo.' },
    ],
    howTo: ['Envoyez votre fichier audio ou vidéo', 'Choisissez une sortie TXT ou SRT', 'Cliquez sur « Transcrire l’audio »', 'Téléchargez le fichier de transcription'],
    intro: 'Envoyez un fichier audio ou vidéo et générez une transcription IA en quelques minutes pour vos notes, résumés, publications ou sous-titres.',
  },
  'auto-subtitle': {
    title: 'Générateur automatique de sous-titres',
    h1: 'Générer des sous-titres automatiquement en ligne',
    description: 'Créer des fichiers de sous-titres à partir d’un audio ou d’une vidéo avec l’IA.',
    metaTitle: 'Générateur de sous-titres automatique en ligne - SRT ou VTT',
    metaDescription: 'Générez automatiquement des sous-titres en ligne avec l’IA. Exportez des fichiers SRT ou VTT à partir d’audios et de vidéos en quelques minutes.',
    actionLabel: 'Générer les sous-titres',
    outputNote: 'Cet outil est adapté aux premiers jets de sous-titres, aux workflows d’accessibilité et aux exports rapides pour montage ou publication.',
    useCases: ['Brouillons de légendes pour YouTube ou réseaux sociaux', 'Fichiers de sous-titres pour l’accessibilité', 'Génération rapide avant relecture manuelle'],
    options: [{ key: 'format', label: 'Format de sortie', type: 'select', options: [{ value: 'srt', label: 'SRT' }, { value: 'vtt', label: 'VTT' }], defaultValue: 'srt' }],
    related: ['transcribe-audio', 'translate-subtitles', 'clean-audio'],
    faq: [
      { q: 'Quels formats de sous-titres sont pris en charge ?', a: 'Vous pouvez exporter des sous-titres en SRT ou en VTT selon votre plateforme de destination.' },
      { q: 'Cela fonctionne-t-il avec des fichiers audio ?', a: 'Oui. Les fichiers audio et vidéo pris en charge fonctionnent tous les deux.' },
      { q: 'Est-ce suffisant pour des sous-titres finaux ?', a: 'C’est idéal pour un premier jet rapide, mais il faut relire les noms, la ponctuation, le minutage et les retours à la ligne avant publication finale.' },
    ],
    howTo: ['Envoyez votre fichier audio ou vidéo', 'Choisissez une sortie SRT ou VTT', 'Cliquez sur « Générer les sous-titres »', 'Téléchargez le fichier de sous-titres'],
    intro: 'Générez automatiquement des sous-titres à partir d’un audio ou d’une vidéo pour publier plus vite et réduire le temps passé sur le premier brouillon.',
  },
  'translate-subtitles': {
    title: 'Traduire un audio en sous-titres',
    h1: 'Traduire un audio en sous-titres en ligne',
    description: 'Générer des sous-titres traduits à partir d’un audio ou d’une vidéo.',
    metaTitle: 'Traduire un audio en sous-titres en ligne',
    metaDescription: 'Envoyez un audio ou une vidéo et générez des sous-titres traduits en ligne en anglais, français ou espagnol au format SRT.',
    actionLabel: 'Traduire les sous-titres',
    outputNote: 'Utilisez la sortie traduite pour la localisation vidéo, les tests de marché, les publications multilingues ou les premiers jets de sous-titres régionaux.',
    useCases: ['Sous-titres traduits pour publication multilingue', 'Brouillons de localisation pour réseaux sociaux ou formation', 'Traduction rapide pour public anglais, français ou espagnol'],
    options: [{ key: 'language', label: 'Langue cible', type: 'select', options: [{ value: 'en', label: 'Anglais' }, { value: 'fr', label: 'Français' }, { value: 'es', label: 'Espagnol' }], defaultValue: 'fr' }],
    related: ['auto-subtitle', 'transcribe-audio', 'clean-audio'],
    faq: [
      { q: 'Quelles langues cibles sont disponibles ?', a: 'Vous pouvez générer des sous-titres traduits en anglais, français ou espagnol.' },
      { q: 'Quel format est exporté ?', a: 'Le résultat traduit est exporté en fichier SRT, facile à relire et à publier.' },
      { q: 'Quand utiliser cet outil plutôt que le générateur de sous-titres ?', a: 'Utilisez-le lorsque votre objectif est la traduction des sous-titres pour une autre audience, et pas seulement la création dans la langue source.' },
    ],
    howTo: ['Envoyez votre fichier audio ou vidéo', 'Choisissez la langue cible', 'Cliquez sur « Traduire les sous-titres »', 'Téléchargez le fichier SRT traduit'],
    intro: 'Envoyez un fichier, choisissez la langue cible et générez automatiquement des sous-titres traduits pour la localisation et la publication multilingue.',
  },
  'clean-audio': {
    title: 'Nettoyer un audio',
    h1: 'Nettoyer un audio en ligne avec l’IA',
    description: 'Réduire le bruit de fond d’un enregistrement vocal en ligne.',
    metaTitle: 'Nettoyer un audio en ligne - Réduction de bruit IA',
    metaDescription: 'Nettoyez un audio en ligne avec une réduction de bruit par IA. Améliorez podcasts, interviews, mémos vocaux et vidéos parlées.',
    actionLabel: 'Nettoyer l’audio',
    outputNote: 'Cet outil réduit le bruit de fond courant pour rendre les enregistrements vocaux plus clairs avant transcription, sous-titrage, montage ou publication.',
    useCases: ['Nettoyage de podcast et de mémo vocal', 'Amélioration d’interviews et de réunions', 'Préparer un fichier bruyant avant transcription'],
    related: ['extract-audio', 'transcribe-audio', 'auto-subtitle'],
    faq: [
      { q: 'Puis-je envoyer une vidéo ?', a: 'Oui. Les fichiers audio et vidéo pris en charge peuvent tous deux être nettoyés.' },
      { q: 'Quel sera le format de sortie ?', a: 'Le résultat nettoyé est exporté en MP3 ou MP4 selon le fichier source.' },
      { q: 'Faut-il nettoyer l’audio avant transcription ?', a: 'Oui, surtout pour les interviews, réunions ou enregistrements bruyants. Une voix plus claire améliore souvent la transcription et les brouillons de sous-titres.' },
    ],
    howTo: ['Envoyez votre fichier audio ou vidéo', 'Cliquez sur « Nettoyer l’audio »', 'Téléchargez le résultat nettoyé'],
    intro: 'Envoyez un fichier audio ou vidéo et supprimez automatiquement le bruit de fond courant avant transcription, sous-titrage, montage ou publication.',
  }

};

const ES_TOOL_TRANSLATIONS: Record<string, Partial<Tool>> = {
  'webm-to-mp4': {
    title: 'Convertir WebM a MP4',
    h1: 'Convertir WebM a MP4 online',
    description: 'Convertir WebM a MP4 online gratis.',
    metaTitle: 'Convertir WebM a MP4 online gratis',
    metaDescription: 'Convertir WebM a MP4 online gratis. Sube tu archivo WebM, conviértelo rápido y descarga tu video MP4. Archivos eliminados automáticamente después de 2 horas.',
    actionLabel: 'Convertir ahora',
    outputNote: 'Tu archivo WebM se convierte a MP4 para una mejor compatibilidad con móviles, portátiles, apps de mensajería y software de edición.',
    useCases: [
      'Reproducir grabaciones del navegador con mayor facilidad en dispositivos Apple y Windows.',
      'Convertir archivos WebM antes de compartirlos en presentaciones o chats.',
      'Preparar reuniones grabadas o capturas de pantalla para plataformas que aceptan mejor MP4.',
    ],
    intro: 'Convierte tus videos WebM al formato MP4, ampliamente compatible. Nuestra herramienta gratuita realiza la conversión de forma segura en la nube, sin instalar software.',
    howTo: ['Sube tu archivo .webm arrastrándolo o haciendo clic en la zona de carga', 'Haz clic en « Convertir ahora » para iniciar el proceso', 'Espera unos segundos mientras termina la conversión', 'Descarga tu archivo MP4 convertido'],
    faq: [
      { q: '¿La conversión de WebM a MP4 es gratis?', a: 'Sí, completamente gratis y sin registro.' },
      { q: '¿Cuánto tarda la conversión?', a: 'La mayoría de los archivos se convierten en menos de un minuto, según su tamaño.' },
      { q: '¿Mis archivos se mantienen privados?', a: 'Sí. Los archivos se eliminan automáticamente después de 2 horas.' },
      { q: '¿Cuál es el tamaño máximo?', a: 'Hasta 200 MB por archivo.' },
    ],
  },
  'mov-to-mp4': {
    title: 'Convertir MOV a MP4',
    h1: 'Convertir MOV a MP4 online',
    description: 'Convertir MOV a MP4 online gratis.',
    metaTitle: 'Convertir MOV a MP4 online gratis',
    metaDescription: 'Convertir MOV a MP4 online gratis. Ideal para videos de iPhone y Mac. Conversión rápida, segura y eliminación automática después de 2 horas.',
    actionLabel: 'Convertir ahora',
    outputNote: 'Los archivos MOV se recodifican a MP4 para que sean más fáciles de subir, editar y reproducir fuera del ecosistema Apple.',
    useCases: [
      'Convertir videos de iPhone o Mac a un formato más portable.',
      'Preparar clips MOV para sitios y aplicaciones que esperan archivos MP4.',
      'Hacer que los archivos creados en Apple sean más fáciles de usar en otros dispositivos.',
    ],
    intro: 'Convierte tus archivos MOV de iPhone, iPad o Mac al formato MP4, compatible con casi cualquier dispositivo.',
    howTo: ['Sube tu archivo .mov', 'Haz clic en « Convertir ahora »', 'Descarga tu archivo MP4'],
    faq: [
      { q: '¿Puedo convertir videos de iPhone?', a: 'Sí. MOV es el formato de video por defecto del iPhone y se convierte muy bien.' },
      { q: '¿Perderé calidad?', a: 'Puede haber una pérdida mínima de calidad con la codificación H.264 estándar, pero normalmente es limitada.' },
    ],
  },
  'mp4-to-mp3': {
    title: 'Convertir MP4 a MP3',
    h1: 'Convertir MP4 a MP3 online',
    description: 'Convertir MP4 a MP3 online y extraer audio gratis.',
    metaTitle: 'Convertir MP4 a MP3 online gratis',
    metaDescription: 'Convertir MP4 a MP3 online gratis. Extrae audio de cualquier video MP4 en unos clics, sin software y con eliminación automática después de 2 horas.',
    actionLabel: 'Extraer audio',
    outputNote: 'La pista de audio se exporta en MP3 para guardar voz, música o entrevistas como un archivo independiente y ligero.',
    useCases: [
      'Guardar clases, podcasts o entrevistas desde archivos de video MP4.',
      'Extraer audio de fondo para escucharlo sin conexión en el móvil.',
      'Crear una versión solo de audio de un webinar o una presentación grabada.',
    ],
    options: [{ key: 'bitrate', label: 'Calidad de audio', type: 'select', options: [{ value: '128k', label: '128 kbps' }, { value: '192k', label: '192 kbps (Recomendado)' }, { value: '320k', label: '320 kbps (Alta)' }], defaultValue: '192k' }],
    intro: 'Extrae el audio de cualquier video MP4 y guárdalo como archivo MP3. Es útil para música, clases, entrevistas y podcasts.',
    howTo: ['Sube tu archivo MP4', 'Elige la calidad de audio (opcional)', 'Haz clic en « Extraer audio »', 'Descarga tu archivo MP3'],
    faq: [
      { q: '¿Qué bitrate tendrá el MP3?', a: 'El valor por defecto es 192 kbps. Puedes elegir 128, 192 o 320 kbps.' },
      { q: '¿Funciona con cualquier archivo MP4?', a: 'Sí, siempre que el archivo MP4 contenga una pista de audio.' },
    ],
  },
  'video-to-mp3': {
    title: 'Convertir video a MP3',
    h1: 'Convertir video a MP3 online',
    description: 'Convertir video a MP3 online gratis.',
    metaTitle: 'Convertir video a MP3 online gratis',
    metaDescription: 'Convertir video a MP3 online gratis. Compatible con MP4, WebM, MOV, AVI y MKV. Rápido, seguro y con eliminación automática después de 2 horas.',
    actionLabel: 'Convertir a MP3',
    outputNote: 'Esta herramienta convierte el audio de varios formatos de video populares en un archivo MP3 estándar fácil de reproducir en la mayoría de dispositivos.',
    useCases: [
      'Convertir entrevistas en video o webinars en audio para escucharlos más tarde.',
      'Extraer la banda sonora de grabaciones en formatos distintos de MP4.',
      'Crear archivos MP3 portátiles a partir de distintas fuentes de video.',
    ],
    intro: 'Extrae audio de formatos de video comunes y obtén un archivo MP3 al instante. Funciona con MP4, WebM, MOV, AVI, MKV y más.',
    howTo: ['Sube cualquier archivo de video', 'Haz clic en « Convertir a MP3 »', 'Descarga tu archivo MP3'],
    faq: [{ q: '¿Qué formatos de video son compatibles?', a: 'Se admiten MP4, WebM, MOV, AVI, MKV, FLV y otros formatos de video comunes.' }],
  },
  'compress-video': {
    title: 'Comprimir video',
    h1: 'Comprimir video online gratis',
    description: 'Comprimir video online y reducir el tamaño gratis.',
    metaTitle: 'Comprimir video online gratis',
    metaDescription: 'Comprimir video online gratis y reducir el tamaño del archivo para correo, subida o almacenamiento. Elige la calidad. Archivos eliminados después de 2 horas.',
    actionLabel: 'Comprimir video',
    outputNote: 'La compresión reduce el tamaño del archivo para facilitar el envío y el almacenamiento, manteniendo la mayor calidad visual posible según el nivel elegido.',
    useCases: [
      'Reducir el tamaño de videos antes de subirlos a formularios, correos o aplicaciones de chat.',
      'Disminuir el espacio de almacenamiento usado por grabaciones de pantalla y clips largos.',
      'Preparar archivos grandes para descargas y transferencias más rápidas.',
    ],
    options: [{ key: 'quality', label: 'Nivel de calidad', type: 'select', options: [{ value: 'high_quality', label: 'Alta calidad (archivo más grande)' }, { value: 'balanced', label: 'Equilibrado (recomendado)' }, { value: 'small_size', label: 'Tamaño pequeño (menor calidad)' }], defaultValue: 'balanced' }],
    intro: 'Reduce el tamaño de tu video online sin configuraciones complicadas. Elige un nivel de calidad y deja que la herramienta haga la compresión.',
    howTo: ['Sube tu archivo de video', 'Selecciona el nivel de compresión', 'Haz clic en « Comprimir video »', 'Descarga el archivo comprimido'],
    faq: [{ q: '¿Cuánto puede reducirse el tamaño del archivo?', a: 'La reducción típica va del 30 % al 70 %, según el archivo original y el nivel de calidad elegido.' }],
  },
  'extract-audio': {
    title: 'Extraer audio de video',
    h1: 'Extraer audio de video online',
    description: 'Extraer audio de video online en MP3, WAV o AAC.',
    metaTitle: 'Extraer audio de video online gratis',
    metaDescription: 'Extraer audio de video online gratis. Exporta tu archivo como MP3, WAV o AAC. Compatible con los formatos de video más usados.',
    actionLabel: 'Extraer audio',
    outputNote: 'Puedes exportar la pista de audio en MP3, WAV o AAC según busques compatibilidad, calidad sin pérdidas o un archivo más compacto.',
    useCases: [
      'Guardar la voz de tutoriales, clases o demostraciones.',
      'Exportar pistas WAV o AAC limpias para edición o reutilización.',
      'Separar voz o música de un video sin software de escritorio.',
    ],
    options: [{ key: 'fmt', label: 'Formato de salida', type: 'select', options: [{ value: 'mp3', label: 'MP3' }, { value: 'wav', label: 'WAV' }, { value: 'aac', label: 'AAC' }], defaultValue: 'mp3' }],
    intro: 'Extrae la pista de audio de un video y guárdala en el formato que prefieras. Se admiten salidas MP3, WAV y AAC.',
    howTo: ['Sube tu archivo de video', 'Elige el formato de audio de salida', 'Haz clic en « Extraer audio »', 'Descarga tu archivo de audio'],
    faq: [{ q: '¿Qué formatos de audio puedo exportar?', a: 'Se admiten MP3, WAV y AAC.' }],
  },
  'remove-audio-from-video': {
    title: 'Quitar audio del video',
    h1: 'Quitar audio del video online',
    description: 'Quitar audio del video online gratis.',
    metaTitle: 'Quitar audio del video online gratis',
    metaDescription: 'Quitar audio del video online gratis y crear un video sin sonido en pocos clics. Procesamiento rápido y eliminación después de 2 horas.',
    actionLabel: 'Quitar audio',
    outputNote: 'La herramienta genera un video MP4 sin sonido para que puedas reutilizar el metraje sin su banda sonora ni su voz original.',
    useCases: [
      'Silenciar videos antes de reutilizarlos en presentaciones o ediciones para redes.',
      'Eliminar audio sensible manteniendo intacta la imagen del video.',
      'Crear clips silenciosos para superposiciones, subtítulos o música de reemplazo.',
    ],
    intro: 'Elimina la pista de audio de un video para crear un archivo silencioso. Es útil para privacidad, remixes, subtítulos o nuevas bandas sonoras.',
    howTo: ['Sube tu video', 'Haz clic en « Quitar audio »', 'Descarga el video silencioso'],
    faq: [{ q: '¿Cambiará la calidad del video?', a: 'Normalmente el flujo de video se copia directamente, por lo que la calidad visual se mantiene igual en la mayoría de los casos.' }],
  },
  'audio-converter': {
    title: 'Convertidor de audio',
    h1: 'Convertidor de audio online',
    description: 'Convertir archivos de audio online entre MP3, WAV, AAC, OGG y FLAC.',
    metaTitle: 'Convertidor de audio online gratis',
    metaDescription: 'Convertidor de audio online gratis para MP3, WAV, AAC, OGG y FLAC. Conversión rápida, segura y eliminación automática después de 2 horas.',
    actionLabel: 'Convertir audio',
    outputNote: 'Elige el formato de salida que mejor se adapte a reproducción, edición, archivo o envío entre los principales estándares de audio.',
    useCases: [
      'Convertir grabaciones a un formato compatible con tu dispositivo de reproducción.',
      'Crear archivos MP3 más ligeros o conservar detalle con FLAC o WAV.',
      'Estandarizar archivos de audio variados antes de publicarlos o editarlos.',
    ],
    options: [{ key: 'target_fmt', label: 'Formato de salida', type: 'select', options: [{ value: 'mp3', label: 'MP3' }, { value: 'wav', label: 'WAV' }, { value: 'aac', label: 'AAC' }, { value: 'ogg', label: 'OGG' }, { value: 'flac', label: 'FLAC' }], defaultValue: 'mp3' }],
    intro: 'Convierte entre los principales formatos de audio online. Sube un archivo, elige el formato de destino y descarga el resultado convertido.',
    howTo: ['Sube tu archivo de audio', 'Elige el formato de salida', 'Haz clic en « Convertir audio »', 'Descarga el archivo convertido'],
    faq: [{ q: '¿Qué formatos de audio son compatibles?', a: 'Se admiten MP3, WAV, AAC, OGG, FLAC y otros formatos de audio comunes.' }],
  },
  'video-converter': {
    title: 'Convertidor de video',
    h1: 'Convertidor de video online',
    description: 'Convertir archivos de video online entre MP4, WebM, MOV, AVI y MKV.',
    metaTitle: 'Convertidor de video online gratis',
    metaDescription: 'Convertidor de video online gratis para MP4, WebM, MOV, AVI y MKV. Conversión rápida, segura y eliminación automática después de 2 horas.',
    actionLabel: 'Convertir video',
    outputNote: 'Puedes convertir formatos de video comunes al formato de salida que necesites para reproducción, subida o edición posterior.',
    useCases: [
      'Cambiar el contenedor de video antes de subirlo a un sitio web o aplicación.',
      'Estandarizar clips procedentes de distintas fuentes en un mismo formato.',
      'Crear versiones MP4 o WebM según tus necesidades de compatibilidad.',
    ],
    options: [{ key: 'target_fmt', label: 'Formato de salida', type: 'select', options: [{ value: 'mp4', label: 'MP4' }, { value: 'webm', label: 'WebM' }], defaultValue: 'mp4' }],
    intro: 'Convierte formatos de video comunes al que necesites. La herramienta acepta entradas MP4, WebM, MOV, AVI y MKV.',
    howTo: ['Sube tu video', 'Elige el formato de salida', 'Haz clic en « Convertir video »', 'Descarga tu video'],
    faq: [{ q: '¿Qué formatos de video son compatibles?', a: 'Se admiten MP4, WebM, MOV, AVI, MKV y otros formatos de video relacionados.' }],
  },
  'trim-video': {
    title: 'Recortar video',
    h1: 'Recortar video online gratis',
    description: 'Recortar video online gratis por tiempo.',
    metaTitle: 'Recortar video online gratis',
    metaDescription: 'Recortar video online gratis. Define la hora de inicio y de fin para extraer el clip que necesitas. Rápido, seguro y con eliminación después de 2 horas.',
    actionLabel: 'Recortar video',
    outputNote: 'El clip de salida conserva solo la sección comprendida entre la hora de inicio y fin que elijas, lo que resulta útil para momentos destacados y ediciones breves.',
    useCases: [
      'Eliminar espacios muertos, errores o pausas largas de una grabación.',
      'Crear clips cortos destacados para compartir o insertar.',
      'Preparar un fragmento más pequeño antes de convertir o comprimir un video.',
    ],
    options: [
      { key: 'start', label: 'Hora de inicio (HH:MM:SS)', type: 'time', defaultValue: '00:00:00' },
      { key: 'end', label: 'Hora de fin (HH:MM:SS)', type: 'time', defaultValue: '00:01:00' },
    ],
    intro: 'Recorta tu video exactamente al fragmento que necesitas definiendo una hora de inicio y fin. Es útil para destacados, extractos y limpiezas rápidas.',
    howTo: ['Sube tu video', 'Introduce la hora de inicio y de fin', 'Haz clic en « Recortar video »', 'Descarga tu clip recortado'],
    faq: [{ q: '¿Qué formato de tiempo debo usar?', a: 'Usa el formato HH:MM:SS; por ejemplo, 00:01:30 para 1 minuto y 30 segundos.' }],
  },
  'transcribe-audio': {
    title: 'Transcribir audio a texto',
    h1: 'Transcribir audio a texto online',
    description: 'Transcripción IA para archivos de audio y video.',
    metaTitle: 'Transcribir audio a texto online - IA gratis',
    metaDescription: 'Transcribe audio o video a texto online con IA. Exporta TXT o SRT desde archivos MP3, MP4, WAV, MOV, M4A y WebM.',
    actionLabel: 'Transcribir audio',
    outputNote: 'Esta herramienta sirve para actas, notas de entrevistas, borradores de subtítulos y primeras versiones de transcripción para editar después.',
    useCases: ['Transcripciones de reuniones y webinars', 'Transcripción de entrevistas', 'Borradores antes de editar subtítulos'],
    options: [{ key: 'format', label: 'Formato de salida', type: 'select', options: [{ value: 'txt', label: 'TXT' }, { value: 'srt', label: 'SRT' }], defaultValue: 'txt' }],
    related: ['auto-subtitle', 'translate-subtitles', 'clean-audio', 'extract-audio'],
    faq: [
      { q: '¿Qué formatos de salida están disponibles?', a: 'Puedes exportar el resultado como TXT para texto legible o como SRT para un flujo listo para subtítulos.' },
      { q: '¿Puedo subir video?', a: 'Sí. Puedes transcribir archivos de audio y video compatibles con el mismo flujo.' },
      { q: '¿Cuándo elegir TXT en lugar de SRT?', a: 'Elige TXT para notas, resúmenes y edición de texto. Elige SRT cuando necesites un archivo importable en una plataforma o editor de video.' },
    ],
    howTo: ['Sube tu archivo de audio o video', 'Elige salida TXT o SRT', 'Haz clic en « Transcribir audio »', 'Descarga el archivo de transcripción'],
    intro: 'Sube un archivo de audio o video y genera una transcripción con IA en minutos para notas, resúmenes, publicación o preparación de subtítulos.',
  },
  'auto-subtitle': {
    title: 'Generador automático de subtítulos',
    h1: 'Generar subtítulos automáticamente online',
    description: 'Crear archivos de subtítulos a partir de audio o video con IA.',
    metaTitle: 'Generador automático de subtítulos online - SRT o VTT',
    metaDescription: 'Genera subtítulos automáticamente online con IA. Exporta archivos SRT o VTT desde audio y video en pocos minutos.',
    actionLabel: 'Generar subtítulos',
    outputNote: 'Esta herramienta es ideal para borradores rápidos de captions, flujos de accesibilidad y exportaciones de subtítulos para edición o publicación.',
    useCases: ['Borradores de captions para YouTube o redes sociales', 'Archivos de subtítulos para accesibilidad', 'Generación rápida antes de la revisión manual'],
    options: [{ key: 'format', label: 'Formato de salida', type: 'select', options: [{ value: 'srt', label: 'SRT' }, { value: 'vtt', label: 'VTT' }], defaultValue: 'srt' }],
    related: ['transcribe-audio', 'translate-subtitles', 'clean-audio'],
    faq: [
      { q: '¿Qué formatos de subtítulos están disponibles?', a: 'Puedes exportar subtítulos en SRT o VTT según dónde vayas a publicarlos o editarlos.' },
      { q: '¿Funciona con archivos de audio?', a: 'Sí. Funcionan tanto archivos de audio como videos compatibles.' },
      { q: '¿Sirve como subtítulo final?', a: 'Es ideal para un primer borrador rápido, pero conviene revisar nombres, puntuación, tiempos y saltos de línea antes de publicarlo.' },
    ],
    howTo: ['Sube tu archivo de audio o video', 'Elige salida SRT o VTT', 'Haz clic en « Generar subtítulos »', 'Descarga el archivo de subtítulos'],
    intro: 'Genera subtítulos automáticamente a partir de audio o video para publicar captions más rápido y reducir el trabajo manual del primer borrador.',
  },
  'translate-subtitles': {
    title: 'Traducir audio a subtítulos',
    h1: 'Traducir audio a subtítulos online',
    description: 'Generar subtítulos traducidos a partir de audio o video.',
    metaTitle: 'Traducir audio a subtítulos online',
    metaDescription: 'Sube audio o video y genera subtítulos traducidos online en inglés, francés o español en formato SRT.',
    actionLabel: 'Traducir subtítulos',
    outputNote: 'Usa la salida traducida para localización de video, pruebas de audiencia, publicación multilingüe o borradores rápidos de subtítulos regionales.',
    useCases: ['Subtítulos traducidos para publicación multilingüe', 'Borradores de localización para redes o formación', 'Traducción rápida para audiencias en inglés, francés o español'],
    options: [{ key: 'language', label: 'Idioma de destino', type: 'select', options: [{ value: 'en', label: 'Inglés' }, { value: 'fr', label: 'Francés' }, { value: 'es', label: 'Español' }], defaultValue: 'fr' }],
    related: ['auto-subtitle', 'transcribe-audio', 'clean-audio'],
    faq: [
      { q: '¿Qué idiomas están disponibles?', a: 'Puedes generar subtítulos traducidos en inglés, francés o español.' },
      { q: '¿Qué formato se exporta?', a: 'El resultado traducido se exporta como archivo SRT para editarlo y publicarlo fácilmente.' },
      { q: '¿Cuándo debo usar esta herramienta en lugar del generador de subtítulos?', a: 'Úsala cuando el objetivo sea traducir subtítulos para otra audiencia y no solo crear subtítulos en el idioma original.' },
    ],
    howTo: ['Sube tu archivo de audio o video', 'Elige el idioma de destino', 'Haz clic en « Traducir subtítulos »', 'Descarga el archivo SRT traducido'],
    intro: 'Sube un archivo, elige el idioma de destino y genera subtítulos traducidos automáticamente para localización y publicación multilingüe.',
  },
  'clean-audio': {
    title: 'Limpiar audio',
    h1: 'Limpiar audio online con IA',
    description: 'Reducir ruido de fondo en grabaciones de voz online.',
    metaTitle: 'Limpiar audio online - Reducción de ruido con IA',
    metaDescription: 'Limpia audio online con reducción de ruido por IA. Mejora podcasts, entrevistas, notas de voz y videos hablados.',
    actionLabel: 'Limpiar audio',
    outputNote: 'Esta herramienta reduce el ruido de fondo habitual para que las grabaciones de voz sean más claras antes de transcribir, subtitular, editar o publicar.',
    useCases: ['Limpieza de podcasts y notas de voz', 'Mejora de entrevistas y reuniones', 'Preparar archivos ruidosos antes de transcribir'],
    related: ['extract-audio', 'transcribe-audio', 'auto-subtitle'],
    faq: [
      { q: '¿Puedo subir video?', a: 'Sí. La herramienta acepta archivos de audio y video compatibles.' },
      { q: '¿Cuál es el formato de salida?', a: 'El resultado limpio se exporta en MP3 o MP4 según el archivo original.' },
      { q: '¿Conviene limpiar el audio antes de transcribir?', a: 'Sí, especialmente en entrevistas, reuniones o grabaciones con ruido. Una voz más clara suele mejorar la transcripción y los borradores de subtítulos.' },
    ],
    howTo: ['Sube tu archivo de audio o video', 'Haz clic en « Limpiar audio »', 'Descarga el resultado limpio'],
    intro: 'Sube un archivo de audio o video y elimina automáticamente el ruido de fondo habitual antes de transcribir, subtitular, editar o publicar.',
  }

};

const TOOL_TRANSLATIONS: Partial<Record<Locale, Record<string, Partial<Tool>>>> = {
  fr: FR_TOOL_TRANSLATIONS,
  es: ES_TOOL_TRANSLATIONS,
};

function localizeTool(tool: Tool, locale: Locale): Tool {
  if (locale === 'en') return tool;
  return { ...tool, ...(TOOL_TRANSLATIONS[locale]?.[tool.slug] || {}) } as Tool;
}

export function getTools(locale: Locale = 'en') {
  return EN_TOOLS.map(tool => localizeTool(tool, locale));
}

export const TOOLS = getTools('en');
export const getToolBySlug = (slug: string, locale: Locale = 'en') => getTools(locale).find(t => t.slug === slug);
export const getAllSlugs = () => EN_TOOLS.map(t => t.slug);
